smallsh: include/error.h File Reference
error.h File Reference
For recording and responding to shell errors.
Functions
void print_error_msg (const char *msg)
Prints an error message to STDOUT.
Variables
volatile int smallsh_errno
Detailed Description
For recording and responding to shell errors.
Author
Mohamed Al-Hussein
Date
04 Feb 2022
Function Documentation
print_error_msg()
void print_error_msg (const char * msg)
Prints an error message to STDOUT.
Parameters
msg message to print
Referenced by main(), smallsh_init(), and smallsh_read_input().
Variable Documentation
smallsh_errno
volatile int smallsh_errno
shell error status code
Referenced by job_control_wait_for_job(), process_launch(), process_set_io_streams(), and status().