smallsh: src/error.c File Reference
error.c File Reference
For recording and responding to shell errors.
#include "error.h"
Functions
void print_error_msg (const char *msg)
Prints an error message to STDOUT.
Detailed Description
For recording and responding to shell errors.
Author
Mohamed Al-Hussein
Date
04 Feb 2022
Definition in file error.c.
Function Documentation
print_error_msg()
void print_error_msg (const char * msg)
Prints an error message to STDOUT.
Parameters
msg message to print
Definition at line 43 of file error.c.
 {
         (void) msg;
 #ifdef DEBUG
         fprintf(stderr, "%s\n", msg);
         fflush(stderr);
 #endif
 }
Referenced by main(), smallsh_init(), and smallsh_read_input().