smallsh: include/events/events.h File Reference
events.h File Reference
Contains functions for handling signal-generated events.
#include "channel.h"
#include "receiver.h"
#include "sender.h"
Functions
void events_cleanup (void)
Cleans up the global event-related data structures.
int events_init (void)
Initializes global event-related data structures.
int events_notify (void)
Consumes new events, notifies user of any them, and removes completed jobs from global job table.
Variables
Channel ch_sigchld
Receiver rcv
Sender snd
Detailed Description
Contains functions for handling signal-generated events.
Author
Mohamed Al-Hussein
Date
09 Feb 2022
Definition in file events.h.
Function Documentation
events_cleanup()
void events_cleanup (void)
Cleans up the global event-related data structures.
Definition at line 82 of file events.c.
 {
         receiver_dtor(&rcv);
         sender_dtor(&snd);
         channel_dtor(&ch_sigchld);
 }
References ch_sigchld, channel_dtor(), rcv, receiver_dtor(), sender_dtor(), and snd.
Referenced by exit_().
events_init()
int events_init (void)
Initializes global event-related data structures.
Returns
0 on success, -1 on failure
Definition at line 42 of file events.c.
 {
         int status;
         /* Initialize event channels */
         status = channel_ctor(&ch_sigchld, receiver_cb_sigchld);
         if (status == -1) {
                 fprintf(stderr, "channel_ctor()");
                 return -1;
         }
         /* Initialize event handler */
         status = receiver_ctor(&rcv, 2);
         if (status == -1) {
                 fprintf(stderr, "receiver_ctor()");
                 return -1;
         }
         status = receiver_add(&rcv, &ch_sigchld);
         if (status == -1) {
                 fprintf(stderr, "receiver_add()");
                 return -1;
         }
         /* Initialize event notifier */
         status = sender_ctor(&snd, 2);
         if (status == -1) {
                 fprintf(stderr, "sender_ctor()");
                 return -1;
         }
         status = sender_add(&snd, &ch_sigchld);
         if (status == -1) {
                 fprintf(stderr, "sender_add()");
                 return -1;
         }
         return 0;
 }
References ch_sigchld, channel_ctor(), rcv, receiver_add(), receiver_cb_sigchld(), receiver_ctor(), sender_add(), sender_ctor(), snd, and status().
Referenced by main().
events_notify()
int events_notify (void)
Consumes new events, notifies user of any them, and removes completed jobs from global job table.
Definition at line 90 of file events.c.
 {
         int status;
         status = receiver_consume_events(&rcv);
         if (status == -1) {
                 fprintf(stderr, "receiver_consume_events()\n");
                 return -1;
         }
         job_table.clean(&job_table);
         return 0;
 }
References JobTable::clean, job_table, rcv, receiver_consume_events(), and status().
Referenced by main().
Variable Documentation
ch_sigchld
Channel ch_sigchld
communication channel for SIGCHLD events
Definition at line 14 of file events.h.
Referenced by events_cleanup(), events_init(), and handler_handle_sigchld().
rcv
Receiver rcv
list of channels waiting on new events
Definition at line 15 of file events.h.
Referenced by events_cleanup(), events_init(), and events_notify().
snd
Sender snd
list of channels to notify on new events
Definition at line 16 of file events.h.
Referenced by events_cleanup(), and events_init().