smallsh: src/events/events.c File Reference
events.c File Reference
Contains functions for handling signal-generated events.
#include <stdio.h>
#include "events/events.h"
#include "job-control/job-control.h"
Macros
#define SH_MAX_EVENTS 1
Functions
int SH_InitEvents (void)
Initializes global event-related data structures.
void SH_CleanupEvents (void)
Cleans up the global event-related data structures.
int SH_NotifyEvents (void)
Consumes new events, notifies user of any them, and removes completed jobs from global job table.
Detailed Description
Contains functions for handling signal-generated events.
Author
Mohamed Al-Hussein
Date
09 Feb 2022
Macro Definition Documentation
SH_MAX_EVENTS
#define SH_MAX_EVENTS 1
Function Documentation
SH_CleanupEvents()
void SH_CleanupEvents (void)
Cleans up the global event-related data structures.
References receiver, sender, SH_DestroyChannel(), SH_DestroyReceiver(), SH_DestroySender(), and sigchld_channel.
Referenced by SH_exit().
SH_InitEvents()
int SH_InitEvents (void)
Initializes global event-related data structures.
Returns
0 on success, -1 on failure
References receiver, sender, SH_CreateChannel(), SH_CreateReceiver(), SH_CreateSender(), SH_MAX_EVENTS, SH_ReceiverAddChannel(), SH_ReceiverSigchldCallbackHandler(), SH_SenderAddChannel(), and sigchld_channel.
Referenced by main().
SH_NotifyEvents()
int SH_NotifyEvents (void)
Consumes new events, notifies user of any them, and removes completed jobs from global job table.
References job_table, receiver, SH_JobTableCleanJobs(), and SH_ReceiverConsumeEvents().
Referenced by main().