smallsh: src/builtins/exit.c File Reference
exit.c File Reference
#include <stdlib.h>
#include <unistd.h>
#include "builtins/exit.h"
#include "events/events.h"
#include "globals.h"
#include "job-control/job-control.h"
Functions
void SH_exit (int const status)
Clean-up all child processes and exit shell.
Function Documentation
SH_exit()
void SH_exit (int status)
Clean-up all child processes and exit shell.
Parameters
status exit SH_status
References job_table, SH_CleanupEvents(), SH_DestroyJobTable(), SH_JobTableKillAllJobs(), and smallsh_interactive_mode.
Referenced by main().