smallsh: include/builtins/exit.h File Reference
exit.h File Reference
exit builtin command.
Functions
void exit_ (int status)
Clean-up all child processes and exit shell.
Detailed Description
exit builtin command.
Author
Mohamed Al-Hussein
Date
04 Feb 2022
Definition in file exit.h.
Function Documentation
exit_()
void exit_ (int status)
Clean-up all child processes and exit shell.
Parameters
status exit status
Definition at line 45 of file exit.c.
 {
         /* Clean up job table and kill any child processes. */
         job_table.killall(&job_table);
         job_table_dtor(&job_table);
         /* Teardown event handling channels. */
         events_cleanup();
         /* Make exit output pretty in case we are operating inside another shell. */
         if (!smallsh_interactive_mode) {
                 write(STDOUT_FILENO, "\n", 1);
         }
         write(STDOUT_FILENO, "exit\n", 5);
         exit(status);
 }
References events_cleanup(), job_table, job_table_dtor(), JobTable::killall, smallsh_interactive_mode, and status().
Referenced by main().