smallsh: src/signals/handler.c File Reference
handler.c File Reference
Contains functions for handling signals.
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "signals/handler.h"
#include "events/events.h"
Macros
#define _GNU_SOURCE
Functions
static void handler_switch_disable_fg_only_mode (void)
Switches SIGTSTP mask to disable fg_only_mode on next receipt.
void SH_HandlerDisableFgOnlyMode (int sig)
Handles a SIGTSTP signal when fg_only_mode is enabled.
void SH_HandlerEnableFgOnlyMode (int sig)
Handles a SIGTSTP signal when fg_only_mode is disabled.
void SH_HandlerHandleSigchld (int sig)
Handles a SIGCHLD signal.
void SH_HandlerSwitchEnableFgOnlyMode (void)
Switches SIGTSTP mask to enable fg_only_mode on next receipt.
Variables
sig_atomic_t smallsh_fg_only_mode_flag = 0
Detailed Description
Contains functions for handling signals.
Author
Mohamed Al-Hussein
Date
04 Feb 2022
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Function Documentation
handler_switch_disable_fg_only_mode()
static void handler_switch_disable_fg_only_mode (void) static
Switches SIGTSTP mask to disable fg_only_mode on next receipt.
Source: https://edstem.org/us/courses/16718/discussion/1067170
References SH_HandlerDisableFgOnlyMode().
Referenced by SH_HandlerEnableFgOnlyMode().
SH_HandlerDisableFgOnlyMode()
void SH_HandlerDisableFgOnlyMode (int sig)
Handles a SIGTSTP signal when fg_only_mode is enabled.
Responds to a SIGTSTP event then calls handler_switch_disable_fg_only_mode() so that the next SIGTSTP event undoes its action.
Source: https://edstem.org/us/courses/16718/discussion/1067170
Parameters
sig signal number
References SH_HandlerSwitchEnableFgOnlyMode(), and smallsh_fg_only_mode_flag.
Referenced by handler_switch_disable_fg_only_mode().
SH_HandlerEnableFgOnlyMode()
void SH_HandlerEnableFgOnlyMode (int sig)
Handles a SIGTSTP signal when fg_only_mode is disabled.
Responds to a SIGTSTP event then calls SH_HandlerSwitchEnableFgOnlyMode() so that the next SIGTSTP event undoes its action.
Source: https://edstem.org/us/courses/16718/discussion/1067170
Parameters
sig signal number
References handler_switch_disable_fg_only_mode(), and smallsh_fg_only_mode_flag.
Referenced by SH_HandlerSwitchEnableFgOnlyMode().
SH_HandlerHandleSigchld()
void SH_HandlerHandleSigchld (int sig)
Handles a SIGCHLD signal.
Makes use of self-pipe trick described in TLPI section 63.5.2 in order to send SIGCHLD information over a pipe, where the job table will consume the data and update its internal state.
Parameters
sig signal number
References SH_SenderNotifySigchldEvent(), and sigchld_channel.
Referenced by SH_InstallerInstallSigchldHandler().
SH_HandlerSwitchEnableFgOnlyMode()
void SH_HandlerSwitchEnableFgOnlyMode (void)
Switches SIGTSTP mask to enable fg_only_mode on next receipt.
Source: https://edstem.org/us/courses/16718/discussion/1067170
References SH_HandlerEnableFgOnlyMode().
Referenced by SH_HandlerDisableFgOnlyMode(), and SH_InstallerInstallSigtstpHandler().
Variable Documentation
smallsh_fg_only_mode_flag
sig_atomic_t smallsh_fg_only_mode_flag = 0
foreground-only flag for handlers
Referenced by SH_HandlerDisableFgOnlyMode(), SH_HandlerEnableFgOnlyMode(), and smallsh_inspect_fg_only_mode_flag().