smallsh: include/signals/handler.h File Reference
handler.h File Reference
Contains functions for handling signals.
Functions
void handler_disable_fg_only_mode (int sig)
Handles a SIGTSTP signal when fg_only_mode is enabled.
void handler_enable_fg_only_mode (int sig)
Handles a SIGTSTP signal when fg_only_mode is disabled.
void handler_handle_sigchld (int sig)
Handles a SIGCHLD signal.
void handler_switch_enable_fg_only_mode (void)
Switches SIGTSTP mask to enable fg_only_mode on next receipt.
Detailed Description
Contains functions for handling signals.
Author
Mohamed Al-Hussein
Date
04 Feb 2022
Definition in file handler.h.
Function Documentation
handler_disable_fg_only_mode()
void handler_disable_fg_only_mode (int sig)
Handles a SIGTSTP signal when fg_only_mode is enabled.
Responds to a SIGTSTP event then calls handler_switch_disable_fg_only_mode() so that the next SIGTSTP event undoes its action.
Source: https://edstem.org/us/courses/16718/discussion/1067170
Parameters
sig signal number
Definition at line 129 of file handler.c.
 {
         (void) sig;
         char fg_off[] = "\nExiting foreground-only mode\n";
         smallsh_fg_only_mode_flag = 0;
         write(STDOUT_FILENO, fg_off, sizeof(fg_off) - 1);
         handler_switch_enable_fg_only_mode();
 }
References handler_switch_enable_fg_only_mode(), and smallsh_fg_only_mode_flag.
Referenced by handler_switch_disable_fg_only_mode().
handler_enable_fg_only_mode()
void handler_enable_fg_only_mode (int sig)
Handles a SIGTSTP signal when fg_only_mode is disabled.
Responds to a SIGTSTP event then calls handler_switch_enable_fg_only_mode() so that the next SIGTSTP event undoes its action.
Source: https://edstem.org/us/courses/16718/discussion/1067170
Parameters
sig signal number
Definition at line 140 of file handler.c.
 {
         (void) sig;
         char fg_on[] = "\nEntering foreground-only mode (& is now ignored)\n";
         smallsh_fg_only_mode_flag = 1;
         write(STDOUT_FILENO, fg_on, sizeof(fg_on) - 1);
         handler_switch_disable_fg_only_mode();
 }
References handler_switch_disable_fg_only_mode(), and smallsh_fg_only_mode_flag.
Referenced by handler_switch_enable_fg_only_mode().
handler_handle_sigchld()
void handler_handle_sigchld (int sig)
Handles a SIGCHLD signal.
Makes use of self-pipe trick described in TLPI section 63.5.2 in order to send SIGCHLD information over a pipe, where the job table will consume the data and update its internal state.
Parameters
sig signal number
Definition at line 151 of file handler.c.
 {
         (void) sig;
         int status, saved_errno;
         saved_errno = errno;
         status = sender_notify_sigchld(ch_sigchld);
         if (status == -1) {
                 fprintf(stderr, "sender_notify_sigchld()");
                 fflush(stderr);
                 _exit(1);
         }
         errno = saved_errno;
 }
References ch_sigchld, sender_notify_sigchld(), and status().
Referenced by installer_install_sigchld_handler().
handler_switch_enable_fg_only_mode()
void handler_switch_enable_fg_only_mode (void)
Switches SIGTSTP mask to enable fg_only_mode on next receipt.
Source: https://edstem.org/us/courses/16718/discussion/1067170
Definition at line 169 of file handler.c.
 {
         struct sigaction sa;
         sigset_t block_set;
         int status;
         /* Ignore SIGCHLD signals within this handler. */
         memset(&sa, 0, sizeof(sa));
         errno = 0;
         status = sigemptyset(&block_set);
         if (status == -1) {
                 perror("sigemptyset");
                 _exit(1);
         }
         errno = 0;
         status = sigaddset(&block_set, SIGCHLD);
         if (status == -1) {
                 perror("sigaddset");
                 _exit(1);
         }
         sa.sa_mask = block_set;
         sa.sa_flags = SA_RESTART;
         sa.sa_handler = handler_enable_fg_only_mode;
         errno = 0;
         status = sigaction(SIGTSTP, &sa, NULL);
         if (status == -1) {
                 perror("sigaction");
                 _exit(1);
         }
 }
References handler_enable_fg_only_mode(), and status().
Referenced by handler_disable_fg_only_mode(), and installer_install_sigtstp_handler().