smallsh: include/signals/installer.h File Reference
installer.h File Reference
Contains functions for installing signals.
Functions
void SH_InstallerInstallJobControlSignals (void)
Installs job control signals for the shell.
void SH_InstallerInstallChildProcessSignals (bool foreground)
Installs process signals for foreground/background child processes.
void SH_InstallerInstallSigchldHandler (void)
Installs a SIGCHLD handler for the shell.
void SH_InstallerInstallSigtstpHandler (void)
Installs a SIGTSTP handler for the shell.
Detailed Description
Contains functions for installing signals.
Author
Mohamed Al-Hussein
Date
05 Feb 2022 Ideas presented here were retrieved from the following sources: https://www.gnu.org/software/libc/manual/html_node/Initializing-the-Shell.html https://www.gnu.org/software/libc/manual/html_node/Launching-Jobs.html
Function Documentation
SH_InstallerInstallChildProcessSignals()
void SH_InstallerInstallChildProcessSignals (bool foreground)
Installs process signals for foreground/background child processes.
Parameters
foreground whether or not process will run in foreground
Referenced by SH_LaunchProcess().
SH_InstallerInstallJobControlSignals()
void SH_InstallerInstallJobControlSignals (void)
Installs job control signals for the shell.
References SH_InstallerInstallSigchldHandler(), and SH_InstallerInstallSigtstpHandler().
Referenced by smallsh_init().
SH_InstallerInstallSigchldHandler()
void SH_InstallerInstallSigchldHandler (void)
Installs a SIGCHLD handler for the shell.
References SH_HandlerHandleSigchld().
Referenced by SH_InstallerInstallJobControlSignals().
SH_InstallerInstallSigtstpHandler()
void SH_InstallerInstallSigtstpHandler (void)
Installs a SIGTSTP handler for the shell.
References SH_HandlerSwitchEnableFgOnlyMode().
Referenced by SH_InstallerInstallJobControlSignals().