smallsh: src/job-control/job-control.c File Reference
job-control.c File Reference
Functions for performing shell job control.
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <sys/wait.h>
#include <termios.h>
#include <unistd.h>
#include "globals.h"
#include "error.h"
#include "job-control/job-control.h"
Macros
#define _GNU_SOURCE
Functions
static void job_control_wait_for_job (Job *job)
static void job_control_background_job (Job *job)
static void job_control_foreground_job (Job *job)
Run job in the foreground.
int job_control_launch_job (Job **job, bool foreground)
Creates new child process and runs job within child.
Detailed Description
Functions for performing shell job control.
Author
Mohamed Al-Hussein
Date
05 Feb 2022 Some of the ideas presented here were retrieved from the following sources: https://www.gnu.org/software/libc/manual/html_node/Launching-Jobs.html https://www.gnu.org/software/libc/manual/html_node/Freground-and-Background.html https://www.gnu.org/software/libc/manual/html_node/Stopped-and-Terminated-Jobs.html
Definition in file job-control.c.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 12 of file job-control.c.
Function Documentation
job_control_background_job()
static void job_control_background_job (Job * job) static
Definition at line 125 of file job-control.c.
 {
         fprintf(stdout, "[%d]\t%d\n", job->job_spec, job->job_proc->proc_pid);
         fflush(stdout);
 }
References Job::job_proc, Job::job_spec, and Process::proc_pid.
Referenced by job_control_launch_job().
job_control_foreground_job()
static void job_control_foreground_job (Job * job) static
Run job in the foreground.
Puts job into the foreground, waits for it to complete, then puts shell back into foreground.
Parameters
job job to run
Definition at line 138 of file job-control.c.
 {
         int status;
         /* Put the job into the foreground. */
         errno = 0;
         status = tcsetpgrp(smallsh_shell_terminal, job->job_pgid);
         if (status == -1) {
                 perror("tcsetpgrp");
                 _exit(1);
         }
         /* Wait for it to report. */
         job_control_wait_for_job(job);
         /* Put the shell back in the foreground. */
         errno = 0;
         status = tcsetpgrp(smallsh_shell_terminal, smallsh_shell_pgid);
         if (status == -1) {
                 perror("tcsetpgrp");
                 _exit(1);
         }
         /* Clear terminal buffers. */
         tcflush(smallsh_shell_terminal, TCIOFLUSH);
 }
References job_control_wait_for_job(), Job::job_pgid, smallsh_shell_pgid, smallsh_shell_terminal, and status().
Referenced by job_control_launch_job().
job_control_launch_job()
int job_control_launch_job (Job ** job, bool foreground)
Creates new child process and runs job within child.
Parameters
job job to run
foreground whether or not the job should run in the foreground
Returns
0 on success, -1 on failure
Definition at line 165 of file job-control.c.
 {
         int status;
         Job *job_;
         pid_t spawn_pid;
         job_ = *job;
         spawn_pid = fork();
         if (spawn_pid == 0) {
                 process_launch(job_->job_proc, job_->job_pgid, job_->job_stdin,
                                job_->job_stdout, foreground);
                 /* If we reach this point, an error occurred. */
                 _exit(1);
         } else if (spawn_pid < 0) {
                 perror("fork");
                 _exit(1);
         } else {
                 /* Put job into its own group and make it the process leader. */
                 job_->job_proc->proc_pid = spawn_pid;
                 if (job_->job_pgid == 0) {
                         job_->job_pgid = spawn_pid;
                 }
                 errno = 0;
                 status = setpgid(spawn_pid, job_->job_pgid);
                 if (status == -1 && errno != EACCES) {
                         perror("setpgid");
                         _exit(1);
                 }
         }
         /* Foreground job. */
         if (foreground) {
                 if (smallsh_interactive_mode) {
                         /*
                          * Give job control over foreground if we are in
                          * interactive mode.
                          */
                         job_control_foreground_job(job_);
                 } else {
                         /* Otherwise, just wait for job to complete. */
                         job_control_wait_for_job(job_);
                 }
         }
         /* Background job. */
         else {
                job_control_background_job(job_);
         }
         return 0;
 }
References job_control_background_job(), job_control_foreground_job(), job_control_wait_for_job(), Job::job_pgid, Job::job_proc, Job::job_stdin, Job::job_stdout, Process::proc_pid, process_launch(), smallsh_interactive_mode, and status().
Referenced by smallsh_eval().
job_control_wait_for_job()
static void job_control_wait_for_job (Job * job) static
Definition at line 29 of file job-control.c.
 {
         int exit_status;
         pid_t child;
         siginfo_t info;
         int opt;
         bool sigtstp_raised, normal_termination;
         int status;
         opt = WEXITED | WSTOPPED | WNOWAIT; /* don't collect child */
         sigtstp_raised = false;
         normal_termination = false;
         exit_status = 0;
         /*
          * Loop until the child process is terminated due to any signal but
          * SIGTSTP. If SIGTSTP is raised, take note and re-raise it once
          * child process is terminated, so that the shell is later notified
          * via its SIGTSTP handler.
          */
         for (;;) {
                 errno = 0;
                 child = waitid(P_PID, job->job_proc->proc_pid, &info, opt);
                 if (child == -1 && errno != ECHILD) {
                         perror("waitid");
                         _exit(1);
                 }
                 /* Child was stopped. */
                 if (info.si_code == CLD_STOPPED) {
                         if (info.si_status == SIGTSTP) {
                                 sigtstp_raised = true;
                                 /*
                                  * We want to ignore SIGTSTP, so collect child,
                                  * resume it, and wait again.
                                  */
                                 errno = 0;
                                 child = waitpid(child, &exit_status, 0);
                                 if (child == -1 && errno != ECHILD) {
                                         perror("waitpid");
                                         _exit(1);
                                 }
                                 errno = 0;
                                 status = kill(child, SIGCONT);
                                 if (status == -1) {
                                         perror("kill");
                                         _exit(1);
                                 }
                         } else {
                                 exit_status = info.si_status;
                                 break;
                         }
                 }
                 /* Child was terminated normally. */
                 else if (info.si_code == CLD_EXITED) {
                         exit_status = info.si_status;
                         normal_termination = true;
                         break;
                 }
                 /* Child was terminated by signal. */
                 else {
                         exit_status = info.si_status;
                         break;
                 }
         }
         if (WIFSIGNALED(exit_status) && !normal_termination) {
                 fprintf(stdout, "terminated by signal %d\n", WTERMSIG(exit_status));
                 fflush(stdout);
         }
         /*
          * Re-raise SIGTSTP signal to shell. This is done because signal
          * handlers are removed when child execs a program, so all we get is a
          * SIGTSTP signal with default behavior.
          */
         if (sigtstp_raised) {
                 errno = 0;
                 status = kill(getpid(), SIGTSTP);
                 if (status == -1) {
                         perror("kill");
                         _exit(1);
                 }
         }
         /*
          * Mark job as completed and update its status so that it can be later
          * removed from the job table and relayed to user.
          */
         job->job_proc->proc_completed = true;
         job->job_proc->proc_status = exit_status;
         smallsh_errno = exit_status;
 }
References Job::job_proc, Process::proc_completed, Process::proc_pid, Process::proc_status, smallsh_errno, and status().
Referenced by job_control_foreground_job(), and job_control_launch_job().