smallsh: src/job-control/job-table.c File Reference
job-table.c File Reference
Contain information about a collection of jobs.
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include "job-control/job-table.h"
Data Structures
struct JobTablePrivate
Contains internal data for JobTable.
Macros
#define _GNU_SOURCE
Functions
static void job_table_add_job_ (struct JobTable const *const self, Job *job)
static void job_table_clean_ (struct JobTable const *const self)
static Job * job_table_find_job_ (struct JobTable const *const self, pid_t job_pgid)
static void job_table_killall_ (struct JobTable const *const self)
static void job_table_list_jobs_ (struct JobTable const *const self)
static int job_table_update_ (struct JobTable const *const self, pid_t pid, int status)
void job_table_ctor (JobTable *self)
Initializes self.
void job_table_dtor (JobTable *self)
De-initializes self and frees up its resources.
Detailed Description
Contain information about a collection of jobs.
Author
Mohamed Al-Hussein
Date
05 Feb 2022 Ideas presented here were retrieved from the following source: https://www.gnu.org/software/libc/manual/html_node/Data-Structures.html
Definition in file job-table.c.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 10 of file job-table.c.
Function Documentation
job_table_add_job_()
static void job_table_add_job_ (struct JobTable const *const self, Job * job) static
Definition at line 65 of file job-table.c.
 {
         struct JobTablePrivate *priv = self->private;
         /* Case 1: Table is empty. */
         if (priv->jt_head == NULL) {
                 priv->jt_head = job;
                 job->job_spec = 1;
         }
         /* Case 2: Table contains at least one job. */
         else {
                 Job *head = priv->jt_head;
                 job->job_next = head;
                 job->job_spec = head->job_spec + 1;
                 priv->jt_head = job;
         }
         priv->jt_job_count++;
 }
References Job::job_next, Job::job_spec, JobTablePrivate::jt_head, and JobTablePrivate::jt_job_count.
Referenced by job_table_ctor().
job_table_clean_()
static void job_table_clean_ (struct JobTable const *const self) static
Definition at line 84 of file job-table.c.
 {
         struct JobTablePrivate *priv = self->private;
         /* Track last and second last jobs for display options. */
         unsigned last_spec_01 = 0;
         unsigned last_spec_02 = 0;
         Job *pre = NULL;
         Job *cur = priv->jt_head;
         while (cur != NULL) {
                 /* Mark last and second last jobs for print display. */
                 if (last_spec_01 == 0) {
                         last_spec_01 = cur->job_spec;
                 } else if (last_spec_02 == 0) {
                         last_spec_02 = cur->job_spec;
                 }
                 /* Remove completed job and print info. */
                 if (cur->job_proc->proc_completed) {
                         /* Background job completed; notify user. */
                         if (cur->job_bg) {
                                 /* Print job info. */
                                 fprintf(stdout, "[%d]", cur->job_spec);
                                 if (cur->job_spec == last_spec_01) {
                                         fprintf(stdout, "+");
                                 } else if (cur->job_spec == last_spec_02) {
                                         fprintf(stdout, "-");
                                 }
                                 fprintf(stdout, "\t%d", cur->job_proc->proc_pid);
                                 fprintf(stdout, "\tDone");
                                 if (cur->job_proc->proc_status == 0) {
                                         fprintf(stdout, "\t\texit value 0");
                                 } else {
                                         fprintf(stdout, "\t\tterminated by signal %d",
                                                cur->job_proc->proc_status);
                                 }
                                 fprintf(stdout, "\t\t%s\n", cur->job_cmd);
                                 fflush(stdout);
                         }
                         /* Remove job and free its memory. */
                         /* Case 1: Job was at list head. */
                         if (cur == priv->jt_head) {
                                 Job *head = priv->jt_head;
                                 priv->jt_head = head->job_next;
                                 job_dtor(head);
                                 free(head);
                                 head = NULL;
                                 cur = priv->jt_head;
                         }
                         /* Case 2: Job was n positions after list head. */
                         else {
                                 Job *old = cur;
                                 pre->job_next = cur->job_next;
                                 cur = pre->job_next;
                                 job_dtor(old);
                                 free(old);
                                 old = NULL;
                         }
                         priv->jt_job_count--;
                 }
                 /* Job is not yet completed. */
                 else {
                         pre = cur;
                         cur = cur->job_next;
                 }
         }
 }
References Job::job_bg, Job::job_cmd, job_dtor(), Job::job_next, Job::job_proc, Job::job_spec, JobTablePrivate::jt_head, JobTablePrivate::jt_job_count, Process::proc_completed, Process::proc_pid, and Process::proc_status.
Referenced by job_table_ctor().
job_table_ctor()
void job_table_ctor (JobTable * self)
Initializes self.
Parameters
self JobTable object to initialize
Definition at line 274 of file job-table.c.
 {
         /* Init table functions. */
         self->add_job = &job_table_add_job_;
         self->clean = &job_table_clean_;
         self->find_job = &job_table_find_job_;
         self->killall = &job_table_killall_;
         self->list_jobs = &job_table_list_jobs_;
         self->update = &job_table_update_;
         /* Init table data. */
         self->private = malloc(sizeof(struct JobTablePrivate));
         self->private->jt_job_count = 0;
         self->private->jt_head = NULL;
 }
References job_table_add_job_(), job_table_clean_(), job_table_find_job_(), job_table_killall_(), job_table_list_jobs_(), and job_table_update_().
Referenced by main().
job_table_dtor()
void job_table_dtor (JobTable * self)
De-initializes self and frees up its resources.
Parameters
self JobTable object to de-initialize
Definition at line 290 of file job-table.c.
 {
         struct JobTablePrivate *priv = self->private;
         /* Free all jobs. */
         while (priv->jt_head != NULL) {
                 Job *head = priv->jt_head;
                 priv->jt_head = head->job_next;
                 job_dtor(head);
                 free(head);
                 head = NULL;
         }
         self->private->jt_job_count = 0;
         /* Reset function pointers. */
         self->add_job = NULL;
         self->clean = NULL;
         self->find_job = NULL;
         self->killall = NULL;
         self->list_jobs = NULL;
         self->update = NULL;
         /* Free table data. */
         free(self->private);
         self->private = NULL;
 }
References job_dtor(), Job::job_next, and JobTablePrivate::jt_head.
Referenced by exit_().
job_table_find_job_()
static Job* job_table_find_job_ (struct JobTable const *const self, pid_t job_pgid) static
Definition at line 161 of file job-table.c.
 {
         struct JobTablePrivate *priv = self->private;
         /* Search all entries for job with matching PGID. */
         Job *job = priv->jt_head;
         while (job != NULL) {
                 if (job->job_pgid == job_pgid) {
                         return job;
                 }
                 job = job->job_next;
         }
         /* Job not found. */
         return NULL;
 }
References Job::job_next, Job::job_pgid, and JobTablePrivate::jt_head.
Referenced by job_table_ctor().
job_table_killall_()
static void job_table_killall_ (struct JobTable const *const self) static
Definition at line 179 of file job-table.c.
 {
         struct JobTablePrivate *priv = self->private;
         Job *job = priv->jt_head;
         while (job != NULL) {
                 pid_t pid = job->job_proc->proc_pid;
                 kill(pid, SIGTERM);
                 job = job->job_next;
         }
         self->clean(self);
 }
References Job::job_next, Job::job_proc, JobTablePrivate::jt_head, and Process::proc_pid.
Referenced by job_table_ctor().
job_table_list_jobs_()
static void job_table_list_jobs_ (struct JobTable const *const self) static
Definition at line 194 of file job-table.c.
 {
         struct JobTablePrivate *priv = self->private;
         Job *job = priv->jt_head;
         while (job != NULL) {
                 printf("JOB:\n"
                        "\tpgid=%d\n"
                        "\tstdin=%s\n"
                        "\tstdout=%s\n"
                        "\tspec=%d\n"
                        "\tPROC:\n"
                        "\t\targv[0]=%s\n"
                        "\t\tpid=%d\n"
                        "\t\tcompleted=%d\n"
                        "\t\tstatus=%d\n",
                        job->job_pgid, job->job_stdin,
                        job->job_stdout, job->job_spec, job->job_proc->argv[0],
                        job->job_proc->proc_pid, job->job_proc->proc_completed,
                        job->job_proc->proc_status);
                 job = job->job_next;
         }
 }
References Process::argv, Job::job_next, Job::job_pgid, Job::job_proc, Job::job_spec, Job::job_stdin, Job::job_stdout, JobTablePrivate::jt_head, Process::proc_completed, Process::proc_pid, and Process::proc_status.
Referenced by job_table_ctor().
job_table_update_()
static int job_table_update_ (struct JobTable const *const self, pid_t pid, int status) static
Definition at line 218 of file job-table.c.
 {
         struct JobTablePrivate *priv = self->private;
         /* Find job with matching PID. */
         Job *job = priv->jt_head;
         while (job != NULL) {
                 if (job->job_proc->proc_pid == pid) {
                         break;
                 }
                 job = job->job_next;
         }
         /* Error! Job not found. */
         if (job == NULL) {
                 return -1;
         }
         /* Update job status. */
         job->job_proc->proc_status = status;
         job->job_proc->proc_completed = true;
         return 0;
 }
References Job::job_next, Job::job_proc, JobTablePrivate::jt_head, Process::proc_completed, Process::proc_pid, Process::proc_status, and status().
Referenced by job_table_ctor().