smallsh: include/job-control/job-table.h File Reference
job-table.h File Reference
Contain information about a collection of jobs.
#include "job.h"
Data Structures
struct SH_JobTable
JobTable object.
Functions
SH_JobTable * SH_CreateJobTable (void)
Initializes new JobTable object.
void SH_DestroyJobTable (SH_JobTable *table)
De-initializes self and frees up its resources.
void SH_JobTableAddJob (SH_JobTable *table, SH_Job *job)
Add a Job to the JobTable.
void SH_JobTableCleanJobs (SH_JobTable *table)
Clean the JobTable, displaying completed job statuses along the way.
SH_Job * SH_JobTableFindJob (SH_JobTable const *table, pid_t job_pgid)
Find a Job within the JobTable that has a matching job_pgid.
void SH_JobTableKillAllJobs (SH_JobTable *table)
Kills all children in JobTable.
void SH_JobTablePrintJobs (SH_JobTable const *table)
List all Jobs in a pretty-printed format.
int SH_JobTableUpdateJob (SH_JobTable const *table, pid_t pid, int status)
Update a Job's SH_status within the JobTable.
Detailed Description
Contain information about a collection of jobs.
Author
Mohamed Al-Hussein
Date
05 Feb 2022 Ideas presented here were retrieved from the following source: https://www.gnu.org/software/libc/manual/html_node/Data-Structures.html
Function Documentation
SH_CreateJobTable()
SH_JobTable* SH_CreateJobTable (void)
Initializes new JobTable object.
Returns
new JobTable object
References SH_JobTable::head, and SH_JobTable::n_jobs.
Referenced by main().
SH_DestroyJobTable()
void SH_DestroyJobTable (SH_JobTable * table)
De-initializes self and frees up its resources.
Parameters
table JobTable object to de-initialize
References SH_JobTable::head, SH_JobTable::n_jobs, SH_Job::next, and SH_DestroyJob().
Referenced by SH_exit().
SH_JobTableAddJob()
void SH_JobTableAddJob (SH_JobTable * table, SH_Job * job)
Add a Job to the JobTable.
Parameters
table JobTable object
job Job object
References SH_JobTable::head, SH_JobTable::n_jobs, SH_Job::next, and SH_Job::spec.
Referenced by smallsh_eval().
SH_JobTableCleanJobs()
void SH_JobTableCleanJobs (SH_JobTable * table)
Clean the JobTable, displaying completed job statuses along the way.
Parameters
table JobTable object
References SH_Job::command, SH_Process::has_completed, SH_JobTable::head, SH_JobTable::n_jobs, SH_Job::next, SH_Process::pid, SH_Job::proc, SH_Job::run_bg, SH_DestroyJob(), SH_Job::spec, and SH_Process::status.
Referenced by SH_JobTableKillAllJobs(), and SH_NotifyEvents().
SH_JobTableFindJob()
SH_Job* SH_JobTableFindJob (SH_JobTable const * table, pid_t job_pgid)
Find a Job within the JobTable that has a matching job_pgid.
Parameters
table JobTable object
job_pgid Job PGID
Returns
Job object if found, NULL if not
References SH_JobTable::head, SH_Job::next, and SH_Job::pgid.
SH_JobTableKillAllJobs()
void SH_JobTableKillAllJobs (SH_JobTable * table)
Kills all children in JobTable.
Called on program exit to clean up any unterminated children the shell created.
Parameters
table JobTable object
References SH_JobTable::head, SH_Job::next, SH_Process::pid, SH_Job::proc, and SH_JobTableCleanJobs().
Referenced by SH_exit().
SH_JobTablePrintJobs()
void SH_JobTablePrintJobs (SH_JobTable const * table)
List all Jobs in a pretty-printed format.
Parameters
table JobTable object
References SH_Process::args, SH_Process::has_completed, SH_JobTable::head, SH_Job::infile, SH_Job::next, SH_Job::outfile, SH_Job::pgid, SH_Process::pid, SH_Job::proc, SH_Job::spec, and SH_Process::status.
SH_JobTableUpdateJob()
int SH_JobTableUpdateJob (SH_JobTable const * table, pid_t pid, int status)
Update a Job's SH_status within the JobTable.
Parameters
table JobTable object
pid Job PID
status SH_status to give Job
Returns
0 if Job was found and updated, -1 otherwise
References SH_Process::has_completed, SH_JobTable::head, SH_Job::next, SH_Process::pid, SH_Job::proc, and SH_Process::status.
Referenced by SH_ReceiverSigchldCallbackHandler().