smallsh: include/job-control/job-control.h File Reference
job-control.h File Reference
Functions for performing shell job control.
#include "job.h"
#include "job-table.h"
Functions
int job_control_launch_job (Job **job, bool foreground)
Creates new child process and runs job within child.
Variables
JobTable job_table
Detailed Description
Functions for performing shell job control.
Author
Mohamed Al-Hussein
Date
05 Feb 2022 Ideas presented here were retrieved from the following sources: https://www.gnu.org/software/libc/manual/html_node/Launching-Jobs.html https://www.gnu.org/software/libc/manual/html_node/Freground-and-Background.html https://www.gnu.org/software/libc/manual/html_node/Stopped-and-Terminated-Jobs.html
Definition in file job-control.h.
Function Documentation
job_control_launch_job()
int job_control_launch_job (Job ** job, bool foreground)
Creates new child process and runs job within child.
Parameters
job job to run
foreground whether or not the job should run in the foreground
Returns
0 on success, -1 on failure
Definition at line 165 of file job-control.c.
 {
         int status;
         Job *job_;
         pid_t spawn_pid;
         job_ = *job;
         spawn_pid = fork();
         if (spawn_pid == 0) {
                 process_launch(job_->job_proc, job_->job_pgid, job_->job_stdin,
                                job_->job_stdout, foreground);
                 /* If we reach this point, an error occurred. */
                 _exit(1);
         } else if (spawn_pid < 0) {
                 perror("fork");
                 _exit(1);
         } else {
                 /* Put job into its own group and make it the process leader. */
                 job_->job_proc->proc_pid = spawn_pid;
                 if (job_->job_pgid == 0) {
                         job_->job_pgid = spawn_pid;
                 }
                 errno = 0;
                 status = setpgid(spawn_pid, job_->job_pgid);
                 if (status == -1 && errno != EACCES) {
                         perror("setpgid");
                         _exit(1);
                 }
         }
         /* Foreground job. */
         if (foreground) {
                 if (smallsh_interactive_mode) {
                         /*
                          * Give job control over foreground if we are in
                          * interactive mode.
                          */
                         job_control_foreground_job(job_);
                 } else {
                         /* Otherwise, just wait for job to complete. */
                         job_control_wait_for_job(job_);
                 }
         }
         /* Background job. */
         else {
                job_control_background_job(job_);
         }
         return 0;
 }
References job_control_background_job(), job_control_foreground_job(), job_control_wait_for_job(), Job::job_pgid, Job::job_proc, Job::job_stdin, Job::job_stdout, Process::proc_pid, process_launch(), smallsh_interactive_mode, and status().
Referenced by smallsh_eval().
Variable Documentation
job_table
JobTable job_table
shell global job-control table
Definition at line 18 of file job-control.h.
Referenced by events_notify(), exit_(), main(), receiver_cb_sigchld(), and smallsh_eval().