smallsh: include/job-control/job.h File Reference
job.h File Reference
Contain information about a a single job.
#include "process.h"
Data Structures
struct SH_Job
Job object.
Typedefs
typedef struct SH_Job SH_Job
Functions
SH_Job * SH_CreateJob (char *command, SH_Process *proc, char *infile, char *outfile, bool run_bg)
Initializes new Job object.
void SH_DestroyJob (SH_Job *job)
Cleans up and frees job resources.
Detailed Description
Contain information about a a single job.
Author
Mohamed Al-Hussein
Date
05 Feb 2022 Ideas presented here were retrieved from the following source: https://www.gnu.org/software/libc/manual/html_node/Data-Structures.html
Typedef Documentation
SH_Job
typedef struct SH_Job SH_Job
Function Documentation
SH_CreateJob()
SH_Job* SH_CreateJob (char * command, SH_Process * proc, char * infile, char * outfile, bool run_bg)
Initializes new Job object.
Parameters
command job command entered by user
proc job's process object
infile job's STDIN filename
outfile job's STDOUT filename
run_bg whether or not job is to be run in background
Returns
new Job object
References SH_Job::command, SH_Job::infile, SH_Job::next, SH_Job::outfile, SH_Job::pgid, SH_Job::proc, and SH_Job::run_bg.
Referenced by smallsh_eval().
SH_DestroyJob()
void SH_DestroyJob (SH_Job * job)
Cleans up and frees job resources.
Parameters
job job to clean up
References SH_Job::command, SH_Job::infile, SH_Job::next, SH_Job::outfile, SH_Job::pgid, SH_Job::proc, SH_Job::run_bg, and SH_DestroyProcess().
Referenced by SH_DestroyJobTable(), and SH_JobTableCleanJobs().