smallsh: src/job-control/job.c File Reference
job.c File Reference
Contain information about a a single job.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "job-control/job.h"
Macros
#define _GNU_SOURCE
Functions
void job_ctor (Job *self, char *cmd, Process *proc, pid_t pgid, char *infile, char *outfile, bool bg)
Initializes values for a Job object.
void job_dtor (Job *self)
Cleans up and frees job resources.
Detailed Description
Contain information about a a single job.
Author
Mohamed Al-Hussein
Date
05 Feb 2022 Ideas presented here were retrieved from the following source: https://www.gnu.org/software/libc/manual/html_node/Data-Structures.html
Definition in file job.c.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 10 of file job.c.
Function Documentation
job_ctor()
void job_ctor (Job * self, char * cmd, Process * proc, pid_t pgid, char * infile, char * outfile, bool bg)
Initializes values for a Job object.
Parameters
self job object to initialize
cmd job command entered by user
proc job's process object
pgid job's PGID
infile job's STDIN filename
outfile job's STDOUT filename
bg whether or not job is to be run in background
Definition at line 47 of file job.c.
 {
         /* Copy job command. */
         self->job_cmd = strdup(cmd);
         if (self->job_cmd == NULL) {
                 fprintf(stderr, "strdup\n");
                 exit(1);
         }
         /* Initialize job variables */
         self->job_proc = proc;
         self->job_pgid = pgid;
         self->job_bg = bg;
         /* Next job is null (for use with job table). */
         self->job_next = NULL;
         /* Copy input/output file names. */
         /* Case 1: Filename is a string. */
         if (infile != NULL) {
                 self->job_stdin = strdup(infile);
                 if (self->job_stdin == NULL) {
                         fprintf(stderr, "strdup\n");
                         exit(1);
                 }
         }
         /* Case 2: Filename is null. */
         else {
                 self->job_stdin = NULL;
         }
         /* Case 1: Filename is a string. */
         if (outfile != NULL) {
                 self->job_stdout = strdup(outfile);
                 if (self->job_stdout == NULL) {
                         fprintf(stderr, "strdup\n");
                         exit(1);
                 }
         }
         /* Case 2: Filename is null. */
         else {
                 self->job_stdout = NULL;
         }
 }
Referenced by smallsh_eval().
job_dtor()
void job_dtor (Job * self)
Cleans up and frees job resources.
Parameters
self job to clean up
Definition at line 94 of file job.c.
 {
         /* Free job command. */
         free(self->job_cmd);
         /* Free process object. */
         process_dtor(self->job_proc);
         free(self->job_proc);
         self->job_proc = NULL;
         /* Clear variables. */
         self->job_pgid = 0;
         self->job_bg = false;
         self->job_next = NULL;
         /* Free input/output file names. */
         free(self->job_stdin);
         self->job_stdin = NULL;
         free(self->job_stdout);
         self->job_stdout = NULL;
 }
References process_dtor().
Referenced by job_table_clean_(), and job_table_dtor().