smallsh: src/interpreter/lexer.c File Reference
lexer.c File Reference
For tokenizing a shell input string.
#include <stdlib.h>
#include "interpreter/lexer.h"
#include "interpreter/shell-tokens.h"
Functions
size_t lexer_generate_tokens (char *buf, size_t max_tok, Token *tok[max_tok])
Given an text stream buf, scans stream and generates Token objects to store in tokens.
Detailed Description
For tokenizing a shell input string.
Author
Mohamed Al-Hussein
Date
26 Jan 2022
Definition in file lexer.c.
Function Documentation
lexer_generate_tokens()
size_t lexer_generate_tokens (char * buf, size_t max_tok, Token * tok[max_tok])
Given an text stream buf, scans stream and generates Token objects to store in tokens.
Parameters
buf text stream to scan
max_tok size of tokens array
tok array of pointers to Token objects to store token data
Returns
number of tokens parsed from stream
Note
Caller should verify that the number of tokens parsed is less than n_tokens. If this is not the case, then input stream was not fully tokenized.
Definition at line 12 of file lexer.c.
 {
         StringIterator iter;
         string_iterator_ctor(&iter, buf);
         size_t count = 0; // number of tokens consumed
         char c1, c2;
         while (iter.vptr->has_next(&iter)) {
                 if (count > max_tok) {
                         // no more space for tokens
                         break;
                 }
                 // peek ahead to next two characters
                 c1 = iter.vptr->peek(&iter, 0);
                 c2 = iter.vptr->peek(&iter, 1);
                 // tokenize value
                 if (IS_WHITESPACE(c1)) {
                         // ignore whitespace
                         iter.vptr->next(&iter);
                         continue;
                 } else if (IS_CMT_SYM(c1)) {
                         if (count == 0) {
                                 // token is a comment
                                 tok[count] = malloc(sizeof(Token));
                                 comment_token_ctor((CommentToken *) tok[count]);
                         } else {
                                 /* Comment symbol is part of a word token. */
                                 goto consume_word;
                         }
                 } else if (IS_INPUT_REDIR_OP(c1, c2)) {
                         // token is an input redirection operator
                         tok[count] = malloc(sizeof(Token));
                         inputredir_token_ctor((InputRedirToken *) tok[count]);
                 } else if (IS_OUTPUT_REDIR_OP(c1, c2)) {
                         // token is an output redirection operator
                         tok[count] = malloc(sizeof(Token));
                         outputredir_token_ctor((OutputRedirToken *) tok[count]);
                 } else if (IS_BG_CTRL_OP(c1, c2)) {
                         // token is a background control operator
                         tok[count] = malloc(sizeof(Token));
                         bgctrl_token_ctor((BGCtrlToken *) tok[count]);
                 } else if (IS_NEWLINE(c1)) {
                         // token is a newline
                         tok[count] = malloc(sizeof(Token));
                         newline_token_ctor((NewlineToken *) tok[count]);
                 } else {
 consume_word:
                         // otherwise, token is a word
                         tok[count] = malloc(sizeof(Token));
                         word_token_ctor((WordToken *) tok[count]);
                 }
                 // consume token
                 ((Token *) tok[count])->vptr->take((Token *) tok[count], &iter);
                 count++;
         }
         string_iterator_dtor(&iter);
         return count;
 }
References bgctrl_token_ctor(), comment_token_ctor(), StringIteratorVtbl::has_next, inputredir_token_ctor(), IS_BG_CTRL_OP, IS_CMT_SYM, IS_INPUT_REDIR_OP, IS_NEWLINE, IS_OUTPUT_REDIR_OP, IS_WHITESPACE, newline_token_ctor(), StringIteratorVtbl::next, outputredir_token_ctor(), StringIteratorVtbl::peek, string_iterator_ctor(), string_iterator_dtor(), StringIterator::vptr, and word_token_ctor().
Referenced by parser_parse_().