smallsh: include/interpreter/lexer.h File Reference
lexer.h File Reference
For tokenizing a shell input string.
#include "shell-tokens.h"
Macros
#define MAX_TOKENS 513 /* 512 max args plus newline */
#define CHAR_SPACE ' '
#define CHAR_TAB '\t'
#define IS_WHITESPACE(c) (c == CHAR_SPACE || c == CHAR_TAB)
#define CHAR_NEWLINE '\n'
#define CHAR_EOL '\0'
#define IS_NEWLINE(c) (c == CHAR_NEWLINE)
#define IS_EOL(c) (c == CHAR_EOL)
#define IS_TERMINAL(c) (IS_WHITESPACE(c) || IS_EOL(c) || IS_NEWLINE(c))
#define INPUT_REDIR_OP '<'
#define OUTPUT_REDIR_OP '>'
#define IS_INPUT_REDIR_OP(c1, c2) (c1 == INPUT_REDIR_OP && IS_TERMINAL(c2))
#define IS_OUTPUT_REDIR_OP(c1, c2) (c1 == OUTPUT_REDIR_OP && IS_TERMINAL(c2))
#define BG_CTRL_OP '&'
#define IS_BG_CTRL_OP(c1, c2) (c1 == BG_CTRL_OP && IS_TERMINAL(c2))
#define CMT_SYM '#'
#define IS_CMT_SYM(c1) (c1 == CMT_SYM)
Functions
size_t lexer_generate_tokens (char *buf, size_t max_tok, Token *tok[max_tok])
Given an text stream buf, scans stream and generates Token objects to store in tokens.
Detailed Description
For tokenizing a shell input string.
Author
Mohamed Al-Hussein
Date
26 Jan 2022
Macro Definition Documentation
BG_CTRL_OP
#define BG_CTRL_OP '&'
CHAR_EOL
#define CHAR_EOL '\0'
CHAR_NEWLINE
#define CHAR_NEWLINE '\n'
CHAR_SPACE
#define CHAR_SPACE ' '
CHAR_TAB
#define CHAR_TAB '\t'
CMT_SYM
#define CMT_SYM '#'
INPUT_REDIR_OP
#define INPUT_REDIR_OP '<'
IS_BG_CTRL_OP
#define IS_BG_CTRL_OP (c1, c2) (c1 == BG_CTRL_OP && IS_TERMINAL(c2))
IS_CMT_SYM
#define IS_CMT_SYM (c1) (c1 == CMT_SYM)
IS_EOL
#define IS_EOL (c) (c == CHAR_EOL)
IS_INPUT_REDIR_OP
#define IS_INPUT_REDIR_OP (c1, c2) (c1 == INPUT_REDIR_OP && IS_TERMINAL(c2))
IS_NEWLINE
#define IS_NEWLINE (c) (c == CHAR_NEWLINE)
IS_OUTPUT_REDIR_OP
#define IS_OUTPUT_REDIR_OP (c1, c2) (c1 == OUTPUT_REDIR_OP && IS_TERMINAL(c2))
IS_TERMINAL
#define IS_TERMINAL (c) (IS_WHITESPACE(c) || IS_EOL(c) || IS_NEWLINE(c))
IS_WHITESPACE
#define IS_WHITESPACE (c) (c == CHAR_SPACE || c == CHAR_TAB)
MAX_TOKENS
#define MAX_TOKENS 513 /* 512 max args plus newline */
OUTPUT_REDIR_OP
#define OUTPUT_REDIR_OP '>'
Function Documentation
lexer_generate_tokens()
size_t lexer_generate_tokens (char * buf, size_t max_tok, Token * tok[max_tok])
Given an text stream buf, scans stream and generates Token objects to store in tokens.
Parameters
buf text stream to scan
max_tok size of tokens array
tok array of pointers to Token objects to store token data
Returns
number of tokens parsed from stream
Note
Caller should verify that the number of tokens parsed is less than n_tokens. If this is not the case, then input stream was not fully tokenized.
References bgctrl_token_ctor(), comment_token_ctor(), StringIteratorVtbl::has_next, inputredir_token_ctor(), IS_BG_CTRL_OP, IS_CMT_SYM, IS_INPUT_REDIR_OP, IS_NEWLINE, IS_OUTPUT_REDIR_OP, IS_WHITESPACE, newline_token_ctor(), StringIteratorVtbl::next, outputredir_token_ctor(), StringIteratorVtbl::peek, string_iterator_ctor(), string_iterator_dtor(), StringIterator::vptr, and word_token_ctor().
Referenced by parser_parse_().