smallsh: include/interpreter/parser.h File Reference
parser.h File Reference
For parsing a stream of tokens into nodes for later evaluation.
#include <sys/types.h>
#include "token-iterator.h"
#include "utils/stack.h"
#include "statement.h"
Data Structures
struct Parser
Defines parser namespace.
Macros
#define is_tok_cmt(tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_CMT)
Determines if a token is a comment token.
#define is_tok_ctrl_bg(tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_CTRL_BG)
Determines if a token is a background control token.
#define is_tok_redir_input(tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_REDIR_INPUT)
Determines if a token is an input redirection token.
#define is_tok_redir_output(tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_REDIR_OUTPUT)
Determines if a token is an output redirection token.
#define is_tok_word(tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_WORD)
Determines if a token is a word token.
#define is_tok_ctrl_newline(tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_CTRL_NEWLINE)
Typedefs
typedef struct Parser Parser
Defines parser namespace.
Functions
void parser_ctor (Parser *self)
Initializes self Parser object.
void parser_dtor (Parser *self)
Destroys self Parser object.
char * parser_expand_word (char *word)
Substitutes all variables in a word string with their literal value, and returns the modified string.
char * parser_insert_pid (char *str, char **ptr, size_t *len)
Extends string with the process's current PID.
char * parser_substitute_variable (char *word, char **old_ptr, char **new_ptr, size_t *len)
Substitutes variable followed by '$' into word and returns result. If no valid variable follows '$', then the '$' is copied into word instead.
Detailed Description
For parsing a stream of tokens into nodes for later evaluation.
Author
Mohamed Al-Hussein
Date
27 Jan 2022
Definition in file parser.h.
Macro Definition Documentation
is_tok_cmt
#define is_tok_cmt (tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_CMT)
Determines if a token is a comment token.
Definition at line 19 of file parser.h.
is_tok_ctrl_bg
#define is_tok_ctrl_bg (tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_CTRL_BG)
Determines if a token is a background control token.
Definition at line 24 of file parser.h.
is_tok_ctrl_newline
#define is_tok_ctrl_newline (tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_CTRL_NEWLINE)
Definition at line 41 of file parser.h.
is_tok_redir_input
#define is_tok_redir_input (tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_REDIR_INPUT)
Determines if a token is an input redirection token.
Definition at line 29 of file parser.h.
is_tok_redir_output
#define is_tok_redir_output (tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_REDIR_OUTPUT)
Determines if a token is an output redirection token.
Definition at line 34 of file parser.h.
is_tok_word
#define is_tok_word (tok) ((ShellTokenType) tok.vptr->get_type(&tok) == TOK_WORD)
Determines if a token is a word token.
Definition at line 39 of file parser.h.
Typedef Documentation
Parser
typedef struct Parser Parser
Defines parser namespace.
Function Documentation
parser_ctor()
void parser_ctor (Parser * self)
Initializes self Parser object.
Parameters
self Parser object to initialize
Definition at line 368 of file parser.c.
 {
         self->parse = &parser_parse_;
         self->get_statements = &parser_get_statements_;
         self->print_statement = &statement_print;
         self->private = malloc(sizeof(struct ParserPrivate));
 }
References parser_get_statements_(), parser_parse_(), and statement_print().
Referenced by smallsh_eval().
parser_dtor()
void parser_dtor (Parser * self)
Destroys self Parser object.
Parameters
self Parser object to destroy
Definition at line 376 of file parser.c.
 {
         for (size_t i = 0; i < self->private->parser_num_tok; i++) {
                 token_dtor(self->private->parser_tok[i]);
                 free(self->private->parser_tok[i]);
                 self->private->parser_tok[i] = NULL;
         }
         free(self->private->parser_tok);
         self->private->parser_num_tok = 0;
         self->private->parser_tok = NULL;
         for (ssize_t i = 0; i < self->private->parser_num_stmt; i++) {
                 statement_del(&self->private->parser_stmt[i]);
         }
         free(self->private->parser_stmt);
         self->private->parser_num_stmt = 0;
         self->private->parser_stmt = NULL;
         free(self->private);
         self->private = NULL;
         self->parse = NULL;
         self->get_statements = NULL;
         self->print_statement = NULL;
 }
References statement_del(), and token_dtor().
Referenced by smallsh_eval().
parser_expand_word()
char* parser_expand_word (char * word)
Substitutes all variables in a word string with their literal value, and returns the modified string.
This is the core expansion step for the parser.
Parameters
word word string to expand variables
Returns
new word string containing literal substitutions for all variables
Definition at line 506 of file parser.c.
 {
         char *new_word, *old_ptr, *new_ptr;
         size_t len;
         /*
          * Allocate space for new word string. At a minimum it will be same
          * length as original word.
          */
         len = strlen(word) + 1;
         new_word = calloc(len, sizeof(char));
         // track copy and insert positions in respective strings
         old_ptr = &word[0];
         new_ptr = &new_word[0];
         /*
          * Copy over every byte from original word to new word, expanding
          * variables when required.
          */
         for (; *old_ptr != '\0'; old_ptr++) {
                 if (*old_ptr == '$') {
                         // attempt to perform variable expansion
                         new_word = parser_substitute_variable(new_word,
                                                               &old_ptr,
                                                               &new_ptr,
                                                               &len);
                 } else {
                         // no expansion needed, so just copy over byte
                         *new_ptr = *old_ptr;
                         new_ptr++;
                 }
         }
         return new_word;
 }
References parser_substitute_variable().
Referenced by parser_parse_cmd_(), and parser_parse_ioredir_().
parser_insert_pid()
char* parser_insert_pid (char * str, char ** ptr, size_t * len)
Extends string with the process's current PID.
This is used during the expansion step of the parser, where '$$' is replaced with the shell process PID.
Precondition
ptr must point to the last character ('\0') in the string. If this is not true, then any remaining bytes after ptr will be overwritten by the PID.
Parameters
str string to extend
ptr pointer to current position in string
len input/output param for final string length
Returns
new string with PID at end, or NULL on error
Definition at line 412 of file parser.c.
 {
         char *result;
         // get pid and convert to string
 #ifdef TEST
         // can't test valid results with randomized pid!
         pid_t pid = 123456;
 #else
         pid_t pid = getpid();
 #endif
         char *pid_str = calloc(sizeof(intmax_t) + 1, sizeof(char));
         if (pid_str == NULL) {
                 return NULL;
         }
         size_t pid_len = snprintf(pid_str, sizeof(intmax_t), "%d", pid);
         if (pid_len >= sizeof(intmax_t)) {
                 free(pid_str);
                 return NULL;
         }
         // save current index since realloc may change string location
         ptrdiff_t idx = *ptr - &str[0];
         // update copy size to fit pid
         size_t new_size = *len + pid_len - 2;
         result = calloc(new_size, sizeof(char));
         if (result == NULL) {
                 free(pid_str);
                 return NULL;
         }
         char *tmp = strncpy(result, str, new_size - 1);
         if (tmp == NULL) {
                 return NULL;
         }
         result = tmp;
         result[new_size - 1] = '\0';
         // reset copy pointer to point to end of result string
         char *new_ptr = &result[0] + idx;
         // extend result string with PID
         for (size_t i = 0; i < pid_len; i++) {
                 *new_ptr++ = pid_str[i];
         }
         *len = new_size;
         *ptr = new_ptr;
         free(pid_str);
         return result;
 }
Referenced by parser_substitute_variable().
parser_substitute_variable()
char* parser_substitute_variable (char * word, char ** old_ptr, char ** new_ptr, size_t * len)
Substitutes variable followed by '$' into word and returns result. If no valid variable follows '$', then the '$' is copied into word instead.
This is used during the expansion step of the parser, where variable substitution is performed. As of now, only PID expansion is supported.
Precondition
old_ptr must point to the first '$' character.
new_pointer must point to the first null ('\0) character in word.
len must be long enough to fit original string characters plus null terminator.
Parameters
word the word string to extend
old_ptr pointer to '$' character in original string
new_ptr pointer to next available character in word for insertion
len input/output parameter for final string length
Returns
new string with variable substituted at end, or just the '$' if no valid variables present
Definition at line 469 of file parser.c.
 {
         char *sub;
         char nxt;
         // peek ahead to first char of variable to determine type
         nxt = (*old_ptr)[1];
         switch (nxt) {
                 case '$':
                 {
                         // replace var with pid
                         sub = parser_insert_pid(word, new_ptr, len);
                         if (sub == NULL) {
                                 return NULL;
                         }
                         // seek past '$'
                         (*old_ptr)++;
                         break;
                 }
                 default:
                 {
                         sub = word;
                         // insert '$' at next available position
                         ptrdiff_t idx = *new_ptr - &sub[0]; // insertion offset
                         sub[idx] = **old_ptr;
                         // seek to next free position
                         (*new_ptr)++;
                         break;
                 }
         }
         return sub;
 }
References parser_insert_pid().
Referenced by parser_expand_word().