smallsh: src/interpreter/parser.c File Reference
parser.c File Reference
For parsing a stream of tokens into nodes for later evaluation.
#include <sys/types.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <unistd.h>
#include <stdint.h>
#include "interpreter/parser.h"
#include "interpreter/token-iterator.h"
#include "interpreter/lexer.h"
#include "builtins/builtins.h"
Data Structures
struct ParserPrivate
Hides Parser members from client code.
Functions
static int parser_parse_cmd_ (Statement *stmt, TokenIterator *iter)
Parses a command into stmt command statement.
static int parser_parse_ioredir_ (Statement *stmt, TokenIterator *iter, IORedirType type)
Parses an io redirection command into stmt command statement.
static ssize_t parser_parse_statements_ (struct Parser *const self)
Parses tokens into statements.
static ssize_t parser_parse_ (Parser *const self, char *buf)
Parses a character stream, creates tokens, and generates command statements.
static Statement ** parser_get_statements_ (struct Parser *const self)
Returns parsed statements to caller.
void parser_ctor (Parser *self)
Initializes self Parser object.
void parser_dtor (Parser *self)
Destroys self Parser object.
char * parser_insert_pid (char *str, char **ptr, size_t *len)
Extends string with the process's current PID.
char * parser_substitute_variable (char *word, char **old_ptr, char **new_ptr, size_t *len)
Substitutes variable followed by '$' into word and returns result. If no valid variable follows '$', then the '$' is copied into word instead.
char * parser_expand_word (char *word)
Substitutes all variables in a word string with their literal value, and returns the modified string.
Detailed Description
For parsing a stream of tokens into nodes for later evaluation.
Author
Mohamed Al-Hussein
Date
27 Jan 2022
Definition in file parser.c.
Function Documentation
parser_ctor()
void parser_ctor (Parser * self)
Initializes self Parser object.
Parameters
self Parser object to initialize
Definition at line 368 of file parser.c.
 {
         self->parse = &parser_parse_;
         self->get_statements = &parser_get_statements_;
         self->print_statement = &statement_print;
         self->private = malloc(sizeof(struct ParserPrivate));
 }
References parser_get_statements_(), parser_parse_(), and statement_print().
Referenced by smallsh_eval().
parser_dtor()
void parser_dtor (Parser * self)
Destroys self Parser object.
Parameters
self Parser object to destroy
Definition at line 376 of file parser.c.
 {
         for (size_t i = 0; i < self->private->parser_num_tok; i++) {
                 token_dtor(self->private->parser_tok[i]);
                 free(self->private->parser_tok[i]);
                 self->private->parser_tok[i] = NULL;
         }
         free(self->private->parser_tok);
         self->private->parser_num_tok = 0;
         self->private->parser_tok = NULL;
         for (ssize_t i = 0; i < self->private->parser_num_stmt; i++) {
                 statement_del(&self->private->parser_stmt[i]);
         }
         free(self->private->parser_stmt);
         self->private->parser_num_stmt = 0;
         self->private->parser_stmt = NULL;
         free(self->private);
         self->private = NULL;
         self->parse = NULL;
         self->get_statements = NULL;
         self->print_statement = NULL;
 }
References statement_del(), and token_dtor().
Referenced by smallsh_eval().
parser_expand_word()
char* parser_expand_word (char * word)
Substitutes all variables in a word string with their literal value, and returns the modified string.
This is the core expansion step for the parser.
Parameters
word word string to expand variables
Returns
new word string containing literal substitutions for all variables
Definition at line 506 of file parser.c.
 {
         char *new_word, *old_ptr, *new_ptr;
         size_t len;
         /*
          * Allocate space for new word string. At a minimum it will be same
          * length as original word.
          */
         len = strlen(word) + 1;
         new_word = calloc(len, sizeof(char));
         // track copy and insert positions in respective strings
         old_ptr = &word[0];
         new_ptr = &new_word[0];
         /*
          * Copy over every byte from original word to new word, expanding
          * variables when required.
          */
         for (; *old_ptr != '\0'; old_ptr++) {
                 if (*old_ptr == '$') {
                         // attempt to perform variable expansion
                         new_word = parser_substitute_variable(new_word,
                                                               &old_ptr,
                                                               &new_ptr,
                                                               &len);
                 } else {
                         // no expansion needed, so just copy over byte
                         *new_ptr = *old_ptr;
                         new_ptr++;
                 }
         }
         return new_word;
 }
References parser_substitute_variable().
Referenced by parser_parse_cmd_(), and parser_parse_ioredir_().
parser_get_statements_()
static Statement** parser_get_statements_ (struct Parser *const self) inline static
Returns parsed statements to caller.
Implementation of Parser::get_statements().
Parameters
self Parser object
Returns
array of Statement objects parsed from character stream
Definition at line 333 of file parser.c.
 {
         return self->private->parser_stmt;
 }
Referenced by parser_ctor().
parser_insert_pid()
char* parser_insert_pid (char * str, char ** ptr, size_t * len)
Extends string with the process's current PID.
This is used during the expansion step of the parser, where '$$' is replaced with the shell process PID.
Precondition
ptr must point to the last character ('\0') in the string. If this is not true, then any remaining bytes after ptr will be overwritten by the PID.
Parameters
str string to extend
ptr pointer to current position in string
len input/output param for final string length
Returns
new string with PID at end, or NULL on error
Definition at line 412 of file parser.c.
 {
         char *result;
         // get pid and convert to string
 #ifdef TEST
         // can't test valid results with randomized pid!
         pid_t pid = 123456;
 #else
         pid_t pid = getpid();
 #endif
         char *pid_str = calloc(sizeof(intmax_t) + 1, sizeof(char));
         if (pid_str == NULL) {
                 return NULL;
         }
         size_t pid_len = snprintf(pid_str, sizeof(intmax_t), "%d", pid);
         if (pid_len >= sizeof(intmax_t)) {
                 free(pid_str);
                 return NULL;
         }
         // save current index since realloc may change string location
         ptrdiff_t idx = *ptr - &str[0];
         // update copy size to fit pid
         size_t new_size = *len + pid_len - 2;
         result = calloc(new_size, sizeof(char));
         if (result == NULL) {
                 free(pid_str);
                 return NULL;
         }
         char *tmp = strncpy(result, str, new_size - 1);
         if (tmp == NULL) {
                 return NULL;
         }
         result = tmp;
         result[new_size - 1] = '\0';
         // reset copy pointer to point to end of result string
         char *new_ptr = &result[0] + idx;
         // extend result string with PID
         for (size_t i = 0; i < pid_len; i++) {
                 *new_ptr++ = pid_str[i];
         }
         *len = new_size;
         *ptr = new_ptr;
         free(pid_str);
         return result;
 }
Referenced by parser_substitute_variable().
parser_parse_()
static ssize_t parser_parse_ (Parser *const self, char * buf) static
Parses a character stream, creates tokens, and generates command statements.
Implementation of Parser::parse().
Parameters
self Parser object
buf character stream to parse
Returns
number of statements created on success, -1 on failure
Note
Caller is responsible for freeing parsed statements via statement_del.
Definition at line 314 of file parser.c.
 {
         // parse stream into tokens
         self->private->parser_tok = malloc(MAX_TOKENS * sizeof(Token));
         self->private->parser_num_tok = lexer_generate_tokens(buf, MAX_TOKENS,
                                                               self->private->parser_tok);
         // parse tokens into statements
         return parser_parse_statements_(self);
 }
References lexer_generate_tokens(), MAX_TOKENS, and parser_parse_statements_().
Referenced by parser_ctor().
parser_parse_cmd_()
static int parser_parse_cmd_ (Statement * stmt, TokenIterator * iter) static
Parses a command into stmt command statement.
Parameters
stmt Statement object to add command to
iter iterator to extract command tokens from
Returns
0 on success, -1 on failure
Definition at line 75 of file parser.c.
 {
         // parse words into statement command
         size_t buf_size = 1;
         while (iter->vptr->has_next(iter)) {
                 Token tok1, tok2;
                 char **tmp;
                 // check if any words left to take
                 tok1 = iter->vptr->peek(iter, 0);
                 tok2 = iter->vptr->peek(iter, 1);
                 if (!is_tok_word(tok1)) {
                         if (is_tok_ctrl_bg(tok1)) {
                                 if (is_tok_ctrl_newline(tok2)) {
                                         break; // done
                                 }
                         } else if (!is_tok_word(tok1)) {
                                 break; // done
                         }
                 }
                 // resize buf if full
                 if (stmt->stmt_cmd->cmd_argc >= buf_size) {
                         buf_size *= 2;
                         tmp = realloc(stmt->stmt_cmd->cmd_argv,
                                       buf_size * sizeof(char *));
                         if (tmp == NULL) {
                                 return -1; // error
                         }
                         stmt->stmt_cmd->cmd_argv = tmp;
                 }
                 // take word
                 WordToken *wt = (WordToken *) iter->vptr->next(iter);
                 char *wt_str = wt->super.vptr->get_value((Token *) wt);
                 stmt->stmt_cmd->cmd_argv[stmt->stmt_cmd->cmd_argc++] =
                         parser_expand_word(wt_str);
                 free(wt_str);
         }
         // resize array to fit exactly argc + 1 elements for later use with exec
         char **tmp = realloc(stmt->stmt_cmd->cmd_argv,
                              (stmt->stmt_cmd->cmd_argc + 1) * sizeof(char *));
         if (tmp == NULL) {
                 return -1; // error
         }
         stmt->stmt_cmd->cmd_argv = tmp;
         // null terminate argv for exec
         stmt->stmt_cmd->cmd_argv[stmt->stmt_cmd->cmd_argc] = NULL;
         /* Check if command is a supported builtin. */
         if (builtins_is_supported(stmt->stmt_cmd->cmd_argv[0])) {
                 stmt->stmt_flags |= FLAGS_BUILTIN;
         }
         return 0;
 }
References builtins_is_supported(), StmtCmd::cmd_argc, StmtCmd::cmd_argv, FLAGS_BUILTIN, TokenVtbl::get_value, TokenIteratorVtbl::has_next, is_tok_ctrl_bg, is_tok_ctrl_newline, is_tok_word, TokenIteratorVtbl::next, parser_expand_word(), TokenIteratorVtbl::peek, Statement::stmt_cmd, Statement::stmt_flags, WordToken::super, TokenIterator::vptr, and Token::vptr.
Referenced by parser_parse_statements_().
parser_parse_ioredir_()
static int parser_parse_ioredir_ (Statement * stmt, TokenIterator * iter, IORedirType type) static
Parses an io redirection command into stmt command statement.
Parameters
stmt Statement object to add io redirection command to
iter iterator to extract io redirection tokens from
type type of io redirection to store
Returns
0 on success, -1 on failure
Definition at line 142 of file parser.c.
 {
         // filename should be a word token
         Token tok = iter->vptr->peek(iter, 1);
         if (!is_tok_word(tok)) {
                 return -1; // error
         }
         // skip past redirection operator
         (void) iter->vptr->next(iter);
         // take next word
         WordToken *wt = (WordToken *) iter->vptr->next(iter);
         // switch to type stream
         char *wt_str;
         char **tmp;
         switch (type) {
                 case IOREDIR_STDIN:
                         // take next word
                         wt_str = wt->super.vptr->get_value((Token *) wt);
                         // extract word string into statement stdin
                         stmt->stmt_stdin->stdin_streams[
                                 stmt->stmt_stdin->stdin_num_streams++] =
                                 parser_expand_word(wt_str);
                         free(wt_str);
                         // resize strings buf
                         tmp = realloc(stmt->stmt_stdin->stdin_streams,
                                       (stmt->stmt_stdin->stdin_num_streams + 1)
                                       * sizeof(char *));
                         if (tmp == NULL) {
                                 return -1; // error
                         }
                         stmt->stmt_stdin->stdin_streams = tmp;
                         stmt->stmt_stdin->stdin_streams[
                                 stmt->stmt_stdin->stdin_num_streams] = NULL;
                         break;
                 case IOREDIR_STDOUT:
                         // take next word
                         wt_str = wt->super.vptr->get_value((Token *) wt);
                         // extract word string into statement stdout
                         stmt->stmt_stdout->stdout_streams[
                                 stmt->stmt_stdout->stdout_num_streams++] =
                                 parser_expand_word(wt_str);
                         free(wt_str);
                         // resize strings buf
                         tmp = realloc(stmt->stmt_stdout->stdout_streams,
                                       (stmt->stmt_stdout->stdout_num_streams + 1)
                                       * sizeof(char *));
                         if (tmp == NULL) {
                                 return -1; // error
                         }
                         stmt->stmt_stdout->stdout_streams = tmp;
                         stmt->stmt_stdout->stdout_streams[
                                 stmt->stmt_stdout->stdout_num_streams] = NULL;
                         break;
                 default:
                         return -1;
         }
         return 0;
 }
References TokenVtbl::get_value, IOREDIR_STDIN, IOREDIR_STDOUT, is_tok_word, TokenIteratorVtbl::next, parser_expand_word(), TokenIteratorVtbl::peek, StmtStdin::stdin_num_streams, StmtStdin::stdin_streams, StmtStdout::stdout_num_streams, StmtStdout::stdout_streams, Statement::stmt_stdin, Statement::stmt_stdout, WordToken::super, TokenIterator::vptr, and Token::vptr.
Referenced by parser_parse_statements_().
parser_parse_statements_()
static ssize_t parser_parse_statements_ (struct Parser *const self) static
Parses tokens into statements.
Parameters
self Parser object
Returns
number of statements created on success, -1 on failure
Definition at line 215 of file parser.c.
 {
         // initialize iterator with token stream
         TokenIterator iter;
         token_iterator_ctor(&iter, self->private->parser_num_tok,
                             self->private->parser_tok);
         // initialize statements array
         size_t buf_size = 1;
         Statement **stmts = malloc(buf_size * sizeof(Statement));
         // evaluate tokens from iterator stream
         ssize_t cur = 1;
         ssize_t count = 0; // number of statements consumed
         while (iter.vptr->has_next(&iter)) {
                 if ((size_t) count >= buf_size) {
                         buf_size *= 2;
                         Statement **tmp = realloc(stmts, buf_size * sizeof(Statement));
                         if (tmp == NULL) {
                                 return -1; // error
                         }
                         stmts = tmp;
                 }
                 Token tok1 = iter.vptr->peek(&iter, 0);
 #ifdef DEMO
                 Token tok2 = iter.vptr->peek(&iter, 1);
 #endif
                 if (is_tok_cmt(tok1)) {
                         break; // done
                 } else if (is_tok_ctrl_bg(tok1)) {
 #ifdef DEMO
                         if (is_tok_ctrl_newline(tok2)) {
                                 (void) iter.vptr->next(&iter);
                                 stmts[count - 1]->stmt_flags |= FLAGS_BGCTRL;
                                 break;
                         }
 #endif
                         if (count == 0) {
                                 // syntax error
                         }
                         (void) iter.vptr->next(&iter);
                         stmts[count - 1]->stmt_flags |= FLAGS_BGCTRL;
                         cur++;
                 } else if (is_tok_ctrl_newline(tok1)) {
                         if (count == 0) {
                                 // empty line
                                 break;
                         }
                         (void) iter.vptr->next(&iter);
                         cur++;
                 } else if (is_tok_redir_input(tok1)) {
                         if (stmts[count] == NULL) {
                                 // syntax error
                         }
                         parser_parse_ioredir_(stmts[count - 1], &iter,
                                               IOREDIR_STDIN);
                 } else if (is_tok_redir_output(tok1)) {
                         if (stmts[count] == NULL) {
                                 // syntax error
                         }
                         parser_parse_ioredir_(stmts[count - 1], &iter,
                                               IOREDIR_STDOUT);
                 } else if (is_tok_word(tok1)) {
                         if (count < cur) {
                                 stmts[count++] = statement_new();
                         } else if (stmts[count]->stmt_stdin->stdin_num_streams > 0 ||
                         stmts[count]->stmt_stdout->stdout_num_streams > 0) {
                                 // syntax error
                                 break;
                         }
                         parser_parse_cmd_(stmts[count - 1], &iter);
                 } else {
                         // do cleanup
                         count = -1;
                         break;
                 }
         }
         token_iterator_dtor(&iter);
         self->private->parser_stmt = stmts;
         self->private->parser_num_stmt = count;
         return count;
 }
References FLAGS_BGCTRL, TokenIteratorVtbl::has_next, IOREDIR_STDIN, IOREDIR_STDOUT, is_tok_cmt, is_tok_ctrl_bg, is_tok_ctrl_newline, is_tok_redir_input, is_tok_redir_output, is_tok_word, TokenIteratorVtbl::next, parser_parse_cmd_(), parser_parse_ioredir_(), TokenIteratorVtbl::peek, TokenIterator::private, statement_new(), StmtStdout::stdout_num_streams, Statement::stmt_flags, Statement::stmt_stdout, token_iterator_ctor(), token_iterator_dtor(), and TokenIterator::vptr.
Referenced by parser_parse_().
parser_substitute_variable()
char* parser_substitute_variable (char * word, char ** old_ptr, char ** new_ptr, size_t * len)
Substitutes variable followed by '$' into word and returns result. If no valid variable follows '$', then the '$' is copied into word instead.
This is used during the expansion step of the parser, where variable substitution is performed. As of now, only PID expansion is supported.
Precondition
old_ptr must point to the first '$' character.
new_pointer must point to the first null ('\0) character in word.
len must be long enough to fit original string characters plus null terminator.
Parameters
word the word string to extend
old_ptr pointer to '$' character in original string
new_ptr pointer to next available character in word for insertion
len input/output parameter for final string length
Returns
new string with variable substituted at end, or just the '$' if no valid variables present
Definition at line 469 of file parser.c.
 {
         char *sub;
         char nxt;
         // peek ahead to first char of variable to determine type
         nxt = (*old_ptr)[1];
         switch (nxt) {
                 case '$':
                 {
                         // replace var with pid
                         sub = parser_insert_pid(word, new_ptr, len);
                         if (sub == NULL) {
                                 return NULL;
                         }
                         // seek past '$'
                         (*old_ptr)++;
                         break;
                 }
                 default:
                 {
                         sub = word;
                         // insert '$' at next available position
                         ptrdiff_t idx = *new_ptr - &sub[0]; // insertion offset
                         sub[idx] = **old_ptr;
                         // seek to next free position
                         (*new_ptr)++;
                         break;
                 }
         }
         return sub;
 }
References parser_insert_pid().
Referenced by parser_expand_word().