smallsh: src/job-control/process.c File Reference
process.c File Reference
Contain information about a single child process.
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "job-control/process.h"
#include "signals/installer.h"
#include "globals.h"
#include "error.h"
Macros
#define _GNU_SOURCE
Functions
static void SH_ExecProcess (char **argv)
Execute program with argv as its arguments.
static void SH_SetProcessGroup (pid_t *pgid)
Creates new process group and assigns current process as the leader.
static int SH_SetProcessIOStreams (char *infile, char *outfile, bool foreground)
Opens IO streams for process.
SH_Process * SH_CreateProcess (size_t n_args, char **args)
Initialize new Process object.
void SH_DestroyProcess (SH_Process *proc)
Reset self to default values and free any associated memory.
void SH_LaunchProcess (SH_Process *proc, pid_t pgid, char *infile, char *outfile, bool foreground)
Launches a new process.
Detailed Description
Contain information about a single child process.
Author
Mohamed Al-Hussein
Date
05 Feb 2022 Some of the ideas presented here were retrieved from the following source: https://www.gnu.org/software/libc/manual/html_node/Launching-Jobs.html
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Function Documentation
SH_CreateProcess()
SH_Process* SH_CreateProcess (size_t n_args, char ** args)
Initialize new Process object.
Parameters
n_args argument count for argv
args array of arguments for process command
Returns
new Process object
References SH_Process::args, SH_Process::has_completed, SH_Process::pid, and SH_Process::status.
Referenced by smallsh_eval().
SH_DestroyProcess()
void SH_DestroyProcess (SH_Process * proc)
Reset self to default values and free any associated memory.
Parameters
proc object to free
References SH_Process::args, SH_Process::has_completed, SH_Process::pid, and SH_Process::status.
Referenced by SH_DestroyJob().
SH_ExecProcess()
static void SH_ExecProcess (char ** argv) static
Execute program with argv as its arguments.
Wrapper around exec* call that executes new program with argv as its arguments, and displays error on failure.
Parameters
argv arguments to pass to exec* function
Referenced by SH_LaunchProcess().
SH_LaunchProcess()
void SH_LaunchProcess (SH_Process * proc, pid_t pgid, char * infile, char * outfile, bool foreground)
Launches a new process.
Parameters
proc process to launch
pgid process PGID
infile STDIN file stream
outfile STDOUT file stream
foreground whether or not the process is to run in the foreground
References SH_Process::args, SH_ExecProcess(), SH_InstallerInstallChildProcessSignals(), SH_SetProcessGroup(), SH_SetProcessIOStreams(), smallsh_errno, smallsh_interactive_mode, and smallsh_shell_terminal.
Referenced by SH_JobControlLaunchJob().
SH_SetProcessGroup()
static void SH_SetProcessGroup (pid_t * pgid) static
Creates new process group and assigns current process as the leader.
Parameters
pgid new process group
Referenced by SH_LaunchProcess().
SH_SetProcessIOStreams()
static int SH_SetProcessIOStreams (char * infile, char * outfile, bool foreground) static
Opens IO streams for process.
STDIN, STDOUT redirected to new streams.
Parameters
infile filename to redirect STDIN to
outfile filename to redirect STDOUT to
foreground whether or not the process will run in foreground
References smallsh_errno.
Referenced by SH_LaunchProcess().