smallsh: include/job-control/process.h File Reference
process.h File Reference
Contain information about a single child process.
#include <stdbool.h>
#include <sys/types.h>
Data Structures
struct Process
A Process object holds information related to running a program.
Functions
void process_ctor (Process *self, size_t argc, char **argv, pid_t pid, bool completed, int status)
Initialize a Process object.
void process_dtor (Process *self)
Reset self to default values and free any associated memory.
void process_launch (Process *proc, pid_t pgid, char *infile, char *outfile, bool foreground)
Launches a new process.
Detailed Description
Contain information about a single child process.
Author
Mohamed Al-Hussein
Date
05 Feb 2022 Ideas presented here were retrieved from the following sources: https://www.gnu.org/software/libc/manual/html_node/Data-Structures.html https://www.gnu.org/software/libc/manual/html_node/Launching-Jobs.html
Definition in file process.h.
Function Documentation
process_ctor()
void process_ctor (Process * self, size_t argc, char ** argv, pid_t pid, bool completed, int status)
Initialize a Process object.
Parameters
self object to initialize
argc argument count for argv
argv array of arguments for process command
pid process PID
completed whether or not the process has completed
status process exit status
Definition at line 225 of file process.c.
 {
         /* Copy over argv array. */
         char **tmp = malloc((argc + 1) * sizeof(char *));
         if (tmp == NULL) {
                 fprintf(stderr, "malloc\n");
                 _exit(1);
         }
         self->argv = tmp;
         for (size_t i = 0; i < argc; i++) {
                 errno = 0;
                 self->argv[i] = strdup(argv[i]);
                 if (self->argv[i] == NULL) {
                         perror("strdup");
                         _exit(1);
                 }
         }
         /* Null-terminate list. */
         self->argv[argc] = NULL;
         /* Initialize remaining variables. */
         self->proc_pid = pid;
         self->proc_completed = completed;
         self->proc_status = status;
 }
References status().
Referenced by smallsh_eval().
process_dtor()
void process_dtor (Process * self)
Reset self to default values and free any associated memory.
Parameters
self object to free
Definition at line 254 of file process.c.
 {
         /* Free argv array. */
         for (size_t i = 0; self->argv[i] != NULL; i++) {
                 free(self->argv[i]);
                 self->argv[i] = NULL;
         }
         free(self->argv);
         self->argv = NULL;
         /* Reset remaining variables. */
         self->proc_pid = 0;
         self->proc_completed = false;
         self->proc_status = 0;
 }
Referenced by job_dtor().
process_launch()
void process_launch (Process * proc, pid_t pgid, char * infile, char * outfile, bool foreground)
Launches a new process.
Parameters
proc process to launch
pgid process PGID
infile STDIN file stream
outfile STDOUT file stream
foreground whether or not the process is to run in the foreground
Definition at line 280 of file process.c.
 {
         int status;
         process_set_group(&pgid);
         if (smallsh_interactive_mode) {
                 /*
                  * If we are running in the foreground, set the process as the
                  * controlling foreground process.
                  */
                 if (foreground) {
                         errno = 0;
                         status = tcsetpgrp(smallsh_shell_terminal, pgid);
                         if (status == -1) {
                                 perror("tcsetpgrp");
                                 _exit(1);
                         }
                 }
         }
         installer_install_child_process_signals(foreground);
         smallsh_errno = 0;
         status = process_set_io_streams(infile, outfile, foreground);
         if (status == -1) {
                 return;
         }
         process_exec(proc->argv);
 }
References Process::argv, installer_install_child_process_signals(), process_exec(), process_set_group(), process_set_io_streams(), smallsh_errno, smallsh_interactive_mode, smallsh_shell_terminal, and status().
Referenced by job_control_launch_job().