smallsh: src/events/sender.c File Reference
sender.c File Reference
Responsible for sending messages to subscribers via a dedicated Channel.
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>
#include "events/sender.h"
#include "events/dto.h"
Functions
SH_Sender * SH_CreateSender (size_t const capacity)
Initializes new Sender object.
void SH_DestroySender (SH_Sender **sender)
int SH_SenderAddChannel (SH_Sender *const sender, SH_Channel *const channel)
Adds a new Channel to its channel list, and initializes its write end.
int SH_SenderNotifySigchldEvent (SH_Channel *const channel)
Detailed Description
Responsible for sending messages to subscribers via a dedicated Channel.
Author
Mohamed Al-Hussein
Date
09 Feb 2022
Function Documentation
SH_CreateSender()
SH_Sender* SH_CreateSender (size_t capacity)
Initializes new Sender object.
Parameters
sender Sender to initialize
capacity maximum number of channels sender will support
Returns
new Sender object on success, NULL on failure
References SH_Sender::capacity, SH_Sender::channels, sender, and SH_Sender::size.
Referenced by SH_InitEvents().
SH_DestroySender()
void SH_DestroySender (SH_Sender ** sender)
References sender.
Referenced by SH_CleanupEvents().
SH_SenderAddChannel()
int SH_SenderAddChannel (SH_Sender * sender, SH_Channel * channel)
Adds a new Channel to its channel list, and initializes its write end.
Behind the scenes, this function initializes the channel pipe's write end and sets it to be non-blocking as per the self-pipe trick requirements.
Parameters
sender Sender to add channel to
channel Channel to add to sender
Returns
0 on success, -1 on failure
References SH_Sender::capacity, SH_Sender::channels, sender, SH_Sender::size, and SH_Channel::write_fd.
Referenced by SH_InitEvents().
SH_SenderNotifySigchldEvent()
int SH_SenderNotifySigchldEvent (SH_Channel *const channel)
References SH_SigchldDTO::pid, SH_SigchldDTO::status, and SH_Channel::write_fd.