smallsh: include/events/sender.h File Reference
sender.h File Reference
Responsible for sending messages to subscribers via a dedicated Channel.
#include "channel.h"
Data Structures
struct Sender
A Sender object consists of an array of Channels that it is responsible for sending messages to on receipt of signal-generated events.
Functions
int sender_add (Sender *self, Channel *ch)
Adds a new Channel to its channel list, and initializes its write end.
int sender_ctor (Sender *self, size_t max_ch)
Initializes self with provided data.
void sender_dtor (Sender *self)
Resets self's values.
int sender_notify_sigchld (struct Channel ch)
Sends data received via a SIGCHLD signal to self.
Detailed Description
Responsible for sending messages to subscribers via a dedicated Channel.
Author
Mohamed Al-Hussein
Date
09 Feb 2022
Definition in file sender.h.
Function Documentation
sender_add()
int sender_add (Sender * self, Channel * ch)
Adds a new Channel to its channel list, and initializes its write end.
Behind the scenes, this function initializes the channel pipe's write end and sets it to be non-blocking as per the self-pipe trick requirements.
Parameters
self Sender to add channel to
ch Channel to add to sender
Returns
0 on success, -1 on failure
Definition at line 88 of file sender.c.
 {
         int flags, status;
         /* Set write end to non-blocking. */
         errno = 0;
         flags = fcntl(ch->ch_write, F_GETFL);
         if (flags == -1) {
                 fprintf(stderr, "Failed to add to Sender: %s\n", strerror(errno));
                 return -1;
         }
         flags |= O_NONBLOCK;
         errno = 0;
         status = fcntl(ch->ch_write, F_SETFL, flags);
         if (status == -1) {
                 fprintf(stderr, "Failed to add to Sender: %s\n", strerror(errno));
                 return -1;
         }
         /* Add channel to channel list. */
         if (self->_snd_n_ch >= self->_snd_max_ch) {
                 fprintf(stderr, "Failed to add to Sender: Sender is full\n");
                 return -1;
         }
         self->_ch[self->_snd_n_ch++] = ch;
         return 0;
 }
References Channel::ch_write, and status().
Referenced by events_init().
sender_ctor()
int sender_ctor (Sender * self, size_t max_ch)
Initializes self with provided data.
Parameters
self Sender to initialize
max_ch maximum number of channels sender will support
Returns
0 on success, -1 on failure
Definition at line 48 of file sender.c.
 {
         self->_snd_n_ch = 0;
         self->_snd_max_ch = max_ch;
         /* Init Channel array. */
         self->_ch = malloc(max_ch * sizeof(Channel));
         if (self->_ch == NULL) {
                 fprintf(stderr, "Failed to init Sender: malloc()\n");
                 return -1;
         }
         for (size_t i = 0; i < max_ch; i++) {
                 self->_ch[i] = NULL;
         }
         return 0;
 }
Referenced by events_init().
sender_dtor()
void sender_dtor (Sender * self)
Resets self's values.
Parameters
self Sender to reset
Note
This does not clear the actual channels by calling their respective destructors. It is the caller's responsibility to do so afterwards.
Definition at line 67 of file sender.c.
 {
         for (size_t i = 0; i < self->_snd_n_ch; i++) {
                 self->_ch[i] = NULL;
         }
         self->_snd_n_ch = 0;
         free(self->_ch);
         self->_ch = NULL;
 }
Referenced by events_cleanup().
sender_notify_sigchld()
int sender_notify_sigchld (struct Channel ch)
Sends data received via a SIGCHLD signal to self.
This function abstracts the signal-handling step used in the self-pipe trick (TLPI section 63.5.2) in an attempt to relay SIGCHLD data while doing its best at remaining async-safe.
Only async-safe system calls are made within this function, and the only global data type that is being accessed within is the pipe's write file descriptor, which is done so for reads only, and without any dereferences. The file descriptor is initialized on program startup, and remains unchanged until program termination.
The data sent is used for updating the shell's global job table, as it requires information on both which child completed and what their exit status was.
Parameters
ch Channel to send data to
Returns
0 on success, -1 on failure
Definition at line 119 of file sender.c.
 {
         int status;
         pid_t child_pid;
         SigchldDTO dto;
         /*
          * Catch all incoming SIGCHLD signals and dispatch their status to
          * listening parties.
          *
          * Source: TLPI section 26.3
          */
         errno = 0;
         while ((child_pid = waitpid(-1, &status, WNOHANG)) > 0) {
                 /* Initialize DTO object to transfer PID and status through. */
                 dto.chld_pid = child_pid;
                 dto.chld_status = status;
                 /* Write DTO to pipe. */
                 errno = 0;
                 if (write(ch.ch_write, &dto, sizeof(dto)) == -1 && errno != EAGAIN) {
                         return -1;
                 }
         }
         if (child_pid == -1 && errno != ECHILD) {
                 return -1;
         }
         return 0;
 }
References Channel::ch_write, SigchldDTO::chld_pid, SigchldDTO::chld_status, and status().
Referenced by handler_handle_sigchld().