smallsh: include/interpreter/shell-tokens.h File Reference
shell-tokens.h File Reference
Definitions for the different types of tokens parsed by the shell.
#include "token.h"
Data Structures
struct BGCtrlToken
Defines a token object that parses and stores background command symbol.
struct CommentToken
Defines a token object that parses and stores a comment symbol.
struct InputRedirToken
Defines a token object that parses and stores an input redirection symbol.
struct NewlineToken
Defines a token object that parses and stores a newline character.
struct OutputRedirToken
Defines a token object that parses and stores an output redirection symbol.
struct WordToken
Defines a token object that parses and stores a command literal.
Enumerations
enum ShellTokenType {
TOK_CMT = 1, TOK_CTRL_BG = 2, TOK_CTRL_NEWLINE = 3, TOK_REDIR_INPUT = 4,
TOK_REDIR_OUTPUT = 5, TOK_WORD = 6, TOK_COUNT = 7
}
Defines the types of tokens our scanner will produce.
Functions
void bgctrl_token_ctor (BGCtrlToken *self)
Constructs a new BackgroundCommandToken object.
void bgctrl_token_dtor (BGCtrlToken *self)
Destroys a BackgroundCommandToken object, freeing its members and re-initializing them to NULL in the process.
void comment_token_ctor (CommentToken *self)
Constructs a new CommentToken object.
void comment_token_dtor (CommentToken *self)
Destroys a CommentToken object, freeing its members and re-initializing them to NULL in the process.
void inputredir_token_ctor (InputRedirToken *self)
Constructs a new InputRedirToken object.
void inputredir_token_dtor (InputRedirToken *self)
Destroys an InputRedirToken object, freeing its members and re-initializing them to NULL in the process.
void newline_token_ctor (NewlineToken *self)
Constructs a new NewlineToken object.
void newline_token_dtor (NewlineToken *self)
Destroys an NewlineToken object, freeing its members and re-initializing them to NULL in the process.
void outputredir_token_ctor (OutputRedirToken *self)
Constructs a new OutputRedirToken object.
void outputredir_token_dtor (OutputRedirToken *self)
Destroys an OutputRedirToken object, freeing its members and re-initializing them to NULL in the process.
void word_token_ctor (WordToken *self)
Constructs a new WordToken object.
void word_token_dtor (WordToken *self)
Destroys a CommandToken object, freeing its members and re-initializing them to NULL in the process.
Detailed Description
Definitions for the different types of tokens parsed by the shell.
Author
Mohamed Al-Hussein
Date
26 Jan 2022
Definition in file shell-tokens.h.
Enumeration Type Documentation
ShellTokenType
enum ShellTokenType
Defines the types of tokens our scanner will produce.
Enumerator
TOK_CMT
a comment is identified by '#' at the start of the stream
TOK_CTRL_BG
a background is identified by '&' at the end of the stream
TOK_CTRL_NEWLINE
a newline is identified by '\n'
TOK_REDIR_INPUT
an input redirection is a '<' to redirect file io
TOK_REDIR_OUTPUT
an output redirection is a '>' to redirect file io
TOK_WORD
a basic token is any word
TOK_COUNT
count of tokens to allow iterating over them
Definition at line 15 of file shell-tokens.h.
              {
         TOK_CMT = 1,
         TOK_CTRL_BG = 2,
         TOK_CTRL_NEWLINE = 3,
         TOK_REDIR_INPUT = 4,
         TOK_REDIR_OUTPUT = 5,
         TOK_WORD = 6,
         TOK_COUNT = 7,
 } ShellTokenType;
Function Documentation
bgctrl_token_ctor()
void bgctrl_token_ctor (BGCtrlToken * self)
Constructs a new BackgroundCommandToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self BackgroundCommandToken object to initialize
Definition at line 269 of file shell-tokens.c.
 {
         static struct TokenVtbl const vtbl = {
                 .get_type = &token_get_type_,
                 .get_value = &token_get_value_,
                 .print = &bgctrl_token_print_,
                 .set_value = &token_set_value_,
                 .take = &bgctrl_token_take_,
         };
         token_ctor(&self->super, (TokenType) TOK_CTRL_BG);
         self->super.vptr = &vtbl;
 }
References bgctrl_token_print_(), bgctrl_token_take_(), TokenVtbl::get_type, TOK_CTRL_BG, token_ctor(), token_get_type_(), token_get_value_(), and token_set_value_().
Referenced by lexer_generate_tokens().
bgctrl_token_dtor()
void bgctrl_token_dtor (BGCtrlToken * self)
Destroys a BackgroundCommandToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self BackgroundCommandToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
Definition at line 282 of file shell-tokens.c.
 {
         token_dtor(&self->super);
 }
References token_dtor().
comment_token_ctor()
void comment_token_ctor (CommentToken * self)
Constructs a new CommentToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self CommentToken object to initialize
Definition at line 287 of file shell-tokens.c.
 {
         static struct TokenVtbl const vtbl = {
                 .get_type = &token_get_type_,
                 .get_value = &token_get_value_,
                 .print = &comment_token_print_,
                 .set_value = &token_set_value_,
                 .take = &comment_token_take_,
         };
         token_ctor(&self->super, (TokenType) TOK_CMT);
         self->super.vptr = &vtbl;
 }
References comment_token_print_(), comment_token_take_(), TokenVtbl::get_type, TOK_CMT, token_ctor(), token_get_type_(), token_get_value_(), and token_set_value_().
Referenced by lexer_generate_tokens().
comment_token_dtor()
void comment_token_dtor (CommentToken * self)
Destroys a CommentToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self CommentToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
Definition at line 300 of file shell-tokens.c.
 {
         token_dtor(&self->super);
 }
References token_dtor().
inputredir_token_ctor()
void inputredir_token_ctor (InputRedirToken * self)
Constructs a new InputRedirToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self InputRedirectionToken object to initialize
Definition at line 305 of file shell-tokens.c.
 {
         static struct TokenVtbl const vtbl = {
                 .get_type = &token_get_type_,
                 .get_value = &token_get_value_,
                 .print = &inputredir_token_print_,
                 .set_value = &token_set_value_,
                 .take = &inputredir_token_take_,
         };
         token_ctor(&self->super, (TokenType) TOK_REDIR_INPUT);
         self->super.vptr = &vtbl;
 }
References TokenVtbl::get_type, inputredir_token_print_(), inputredir_token_take_(), TOK_REDIR_INPUT, token_ctor(), token_get_type_(), token_get_value_(), and token_set_value_().
Referenced by lexer_generate_tokens().
inputredir_token_dtor()
void inputredir_token_dtor (InputRedirToken * self)
Destroys an InputRedirToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self InputRedirToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
Definition at line 318 of file shell-tokens.c.
 {
         token_dtor(&self->super);
 }
References token_dtor().
newline_token_ctor()
void newline_token_ctor (NewlineToken * self)
Constructs a new NewlineToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self NewlineToken object to initialize
Definition at line 323 of file shell-tokens.c.
 {
         static struct TokenVtbl const vtbl = {
                 .get_type = &token_get_type_,
                 .get_value = &token_get_value_,
                 .print = &newline_token_print_,
                 .set_value = &token_set_value_,
                 .take = &newline_token_take_,
         };
         token_ctor(&self->super, (TokenType) TOK_CTRL_NEWLINE);
         self->super.vptr = &vtbl;
 }
References TokenVtbl::get_type, newline_token_print_(), newline_token_take_(), TOK_CTRL_NEWLINE, token_ctor(), token_get_type_(), token_get_value_(), and token_set_value_().
Referenced by lexer_generate_tokens(), and token_iterator_peek_().
newline_token_dtor()
void newline_token_dtor (NewlineToken * self)
Destroys an NewlineToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self NewlineToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
Definition at line 336 of file shell-tokens.c.
 {
         token_dtor(&self->super);
 }
References token_dtor().
outputredir_token_ctor()
void outputredir_token_ctor (OutputRedirToken * self)
Constructs a new OutputRedirToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self OutputRedirToken object to initialize
Definition at line 341 of file shell-tokens.c.
 {
         static struct TokenVtbl const vtbl = {
                 .get_type = &token_get_type_,
                 .get_value = &token_get_value_,
                 .print = &outputredir_token_print_,
                 .set_value = &token_set_value_,
                 .take = &outputredir_token_take_,
         };
         token_ctor(&self->super, (TokenType) TOK_REDIR_OUTPUT);
         self->super.vptr = &vtbl;
 }
References TokenVtbl::get_type, outputredir_token_print_(), outputredir_token_take_(), TOK_REDIR_OUTPUT, token_ctor(), token_get_type_(), token_get_value_(), and token_set_value_().
Referenced by lexer_generate_tokens().
outputredir_token_dtor()
void outputredir_token_dtor (OutputRedirToken * self)
Destroys an OutputRedirToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self OutputRedirToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
Definition at line 354 of file shell-tokens.c.
 {
         token_dtor(&self->super);
 }
References token_dtor().
word_token_ctor()
void word_token_ctor (WordToken * self)
Constructs a new WordToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self WordToken object to initialize
Definition at line 359 of file shell-tokens.c.
 {
         static struct TokenVtbl const vtbl = {
                 .get_type = &token_get_type_,
                 .get_value = &token_get_value_,
                 .print = &word_token_print_,
                 .set_value = &token_set_value_,
                 .take = &word_token_take_,
         };
         token_ctor(&self->super, (TokenType) TOK_WORD);
         self->super.vptr = &vtbl;
 }
References TokenVtbl::get_type, TOK_WORD, token_ctor(), token_get_type_(), token_get_value_(), token_set_value_(), word_token_print_(), and word_token_take_().
Referenced by lexer_generate_tokens().
word_token_dtor()
void word_token_dtor (WordToken * self)
Destroys a CommandToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self CommandToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
Definition at line 372 of file shell-tokens.c.
 {
         token_dtor(&self->super);
 }
References token_dtor().