smallsh: src/interpreter/shell-tokens.c File Reference
shell-tokens.c File Reference
For parsing and storing the different types of tokens of the shell.
#include <stdio.h>
#include <stdlib.h>
#include "interpreter/shell-tokens.h"
Functions
static void bgctrl_token_print_ (Token const *const self)
Implementation of BGControlToken::Token::print().
static void bgctrl_token_take_ (Token const *const self, StringIterator const *const iter)
Implementation of BGControlToken::Token::take().
static void comment_token_print_ (Token const *const self)
Implementation of CommentToken::Token::print().
static void comment_token_take_ (Token const *const self, StringIterator const *const iter)
Implementation of CommentToken::Token::take().
static void inputredir_token_print_ (Token const *const self)
Implementation of InputRedirToken::Token::print().
static void inputredir_token_take_ (Token const *const self, StringIterator const *const iter)
Implementation of InputRedirToken::Token::take().
static void newline_token_print_ (Token const *const self)
Implementation of NewlineToken::Token::print().
static void newline_token_take_ (Token const *const self, StringIterator const *const iter)
Implementation of NewlineToken::Token::take().
static void outputredir_token_print_ (Token const *const self)
Implementation of OutputRedirToken::Token::print().
static void outputredir_token_take_ (Token const *const self, StringIterator const *const iter)
Implementation of OutputRedirToken::Token::take().
static void word_token_print_ (Token const *const self)
Implementation of WordToken::Token::print().
static void word_token_take_ (Token const *const self, StringIterator const *const iter)
Implementation of WordToken::Token::take().
void bgctrl_token_ctor (BGCtrlToken *self)
Constructs a new BackgroundCommandToken object.
void bgctrl_token_dtor (BGCtrlToken *self)
Destroys a BackgroundCommandToken object, freeing its members and re-initializing them to NULL in the process.
void comment_token_ctor (CommentToken *self)
Constructs a new CommentToken object.
void comment_token_dtor (CommentToken *self)
Destroys a CommentToken object, freeing its members and re-initializing them to NULL in the process.
void inputredir_token_ctor (InputRedirToken *self)
Constructs a new InputRedirToken object.
void inputredir_token_dtor (InputRedirToken *self)
Destroys an InputRedirToken object, freeing its members and re-initializing them to NULL in the process.
void newline_token_ctor (NewlineToken *self)
Constructs a new NewlineToken object.
void newline_token_dtor (NewlineToken *self)
Destroys an NewlineToken object, freeing its members and re-initializing them to NULL in the process.
void outputredir_token_ctor (OutputRedirToken *self)
Constructs a new OutputRedirToken object.
void outputredir_token_dtor (OutputRedirToken *self)
Destroys an OutputRedirToken object, freeing its members and re-initializing them to NULL in the process.
void word_token_ctor (WordToken *self)
Constructs a new WordToken object.
void word_token_dtor (WordToken *self)
Destroys a CommandToken object, freeing its members and re-initializing them to NULL in the process.
Detailed Description
For parsing and storing the different types of tokens of the shell.
Author
Mohamed Al-Hussein
Date
26 Jan 2022
Function Documentation
bgctrl_token_ctor()
void bgctrl_token_ctor (BGCtrlToken * self)
Constructs a new BackgroundCommandToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self BackgroundCommandToken object to initialize
References bgctrl_token_print_(), bgctrl_token_take_(), TokenVtbl::get_type, TOK_CTRL_BG, token_ctor(), token_get_type_(), token_get_value_(), and token_set_value_().
Referenced by lexer_generate_tokens().
bgctrl_token_dtor()
void bgctrl_token_dtor (BGCtrlToken * self)
Destroys a BackgroundCommandToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self BackgroundCommandToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
References token_dtor().
bgctrl_token_print_()
static void bgctrl_token_print_ (Token const *const self) static
Implementation of BGControlToken::Token::print().
Prints a pretty formatted display of the Token object.
Parameters
self pointer to BGControlToken object
References TokenVtbl::get_value, BGCtrlToken::super, and Token::vptr.
Referenced by bgctrl_token_ctor().
bgctrl_token_take_()
static void bgctrl_token_take_ (Token const *const self, StringIterator const *const iter) static
Implementation of BGControlToken::Token::take().
Iterates over a single character and then stores the copy.
Precondition
It is the caller's responsibility to ensure that the data being copied over is indeed a background command token.
Parameters
self pointer to BGControlToken object
iter pointer to StringIterator object
References StringIteratorVtbl::munch_char, TokenVtbl::set_value, BGCtrlToken::super, Token::vptr, and StringIterator::vptr.
Referenced by bgctrl_token_ctor().
comment_token_ctor()
void comment_token_ctor (CommentToken * self)
Constructs a new CommentToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self CommentToken object to initialize
References comment_token_print_(), comment_token_take_(), TokenVtbl::get_type, TOK_CMT, token_ctor(), token_get_type_(), token_get_value_(), and token_set_value_().
Referenced by lexer_generate_tokens().
comment_token_dtor()
void comment_token_dtor (CommentToken * self)
Destroys a CommentToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self CommentToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
References token_dtor().
comment_token_print_()
static void comment_token_print_ (Token const *const self) static
Implementation of CommentToken::Token::print().
Prints a pretty formatted display of the Token object.
Parameters
self pointer to CommentToken object
References TokenVtbl::get_value, CommentToken::super, and Token::vptr.
Referenced by comment_token_ctor().
comment_token_take_()
static void comment_token_take_ (Token const *const self, StringIterator const *const iter) static
Implementation of CommentToken::Token::take().
Iterates over a single character and then stores the copy.
Precondition
It is the caller's responsibility to ensure that the data being copied over is indeed a comment token.
Parameters
self pointer to CommentToken object
iter pointer to StringIterator object
References StringIteratorVtbl::munch_char, TokenVtbl::set_value, CommentToken::super, Token::vptr, and StringIterator::vptr.
Referenced by comment_token_ctor().
inputredir_token_ctor()
void inputredir_token_ctor (InputRedirToken * self)
Constructs a new InputRedirToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self InputRedirectionToken object to initialize
References TokenVtbl::get_type, inputredir_token_print_(), inputredir_token_take_(), TOK_REDIR_INPUT, token_ctor(), token_get_type_(), token_get_value_(), and token_set_value_().
Referenced by lexer_generate_tokens().
inputredir_token_dtor()
void inputredir_token_dtor (InputRedirToken * self)
Destroys an InputRedirToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self InputRedirToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
References token_dtor().
inputredir_token_print_()
static void inputredir_token_print_ (Token const *const self) static
Implementation of InputRedirToken::Token::print().
Prints a pretty formatted display of the Token object.
Parameters
self pointer to InputRedirToken object
References TokenVtbl::get_value, InputRedirToken::super, and Token::vptr.
Referenced by inputredir_token_ctor().
inputredir_token_take_()
static void inputredir_token_take_ (Token const *const self, StringIterator const *const iter) static
Implementation of InputRedirToken::Token::take().
Iterates over a single character and then stores the copy.
Precondition
It is the caller's responsibility to ensure that the data being copied over is indeed an input redirection token.
Parameters
self pointer to InputRedirToken object
iter pointer to StringIterator object
References StringIteratorVtbl::munch_char, TokenVtbl::set_value, InputRedirToken::super, Token::vptr, and StringIterator::vptr.
Referenced by inputredir_token_ctor().
newline_token_ctor()
void newline_token_ctor (NewlineToken * self)
Constructs a new NewlineToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self NewlineToken object to initialize
References TokenVtbl::get_type, newline_token_print_(), newline_token_take_(), TOK_CTRL_NEWLINE, token_ctor(), token_get_type_(), token_get_value_(), and token_set_value_().
Referenced by lexer_generate_tokens(), and token_iterator_peek_().
newline_token_dtor()
void newline_token_dtor (NewlineToken * self)
Destroys an NewlineToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self NewlineToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
References token_dtor().
newline_token_print_()
static void newline_token_print_ (Token const *const self) static
Implementation of NewlineToken::Token::print().
Prints a pretty formatted display of the Token object.
Parameters
self pointer to NewlineToken object
Referenced by newline_token_ctor().
newline_token_take_()
static void newline_token_take_ (Token const *const self, StringIterator const *const iter) static
Implementation of NewlineToken::Token::take().
Iterates over a single character and then stores the copy.
Precondition
It is the caller's responsibility to ensure that the data being copied over is indeed an output redirection token.
Parameters
self pointer to NewlineToken object
iter pointer to StringIterator object
References StringIteratorVtbl::munch_char, TokenVtbl::set_value, NewlineToken::super, Token::vptr, and StringIterator::vptr.
Referenced by newline_token_ctor().
outputredir_token_ctor()
void outputredir_token_ctor (OutputRedirToken * self)
Constructs a new OutputRedirToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self OutputRedirToken object to initialize
References TokenVtbl::get_type, outputredir_token_print_(), outputredir_token_take_(), TOK_REDIR_OUTPUT, token_ctor(), token_get_type_(), token_get_value_(), and token_set_value_().
Referenced by lexer_generate_tokens().
outputredir_token_dtor()
void outputredir_token_dtor (OutputRedirToken * self)
Destroys an OutputRedirToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self OutputRedirToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
References token_dtor().
outputredir_token_print_()
static void outputredir_token_print_ (Token const *const self) static
Implementation of OutputRedirToken::Token::print().
Prints a pretty formatted display of the Token object.
Parameters
self pointer to OutputRedirToken object
References TokenVtbl::get_value, OutputRedirToken::super, and Token::vptr.
Referenced by outputredir_token_ctor().
outputredir_token_take_()
static void outputredir_token_take_ (Token const *const self, StringIterator const *const iter) static
Implementation of OutputRedirToken::Token::take().
Iterates over a single character and then stores the copy.
Precondition
It is the caller's responsibility to ensure that the data being copied over is indeed an output redirection token.
Parameters
self pointer to OutputRedirToken object
iter pointer to StringIterator object
References StringIteratorVtbl::munch_char, TokenVtbl::set_value, OutputRedirToken::super, Token::vptr, and StringIterator::vptr.
Referenced by outputredir_token_ctor().
word_token_ctor()
void word_token_ctor (WordToken * self)
Constructs a new WordToken object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self WordToken object to initialize
References TokenVtbl::get_type, TOK_WORD, token_ctor(), token_get_type_(), token_get_value_(), token_set_value_(), word_token_print_(), and word_token_take_().
Referenced by lexer_generate_tokens().
word_token_dtor()
void word_token_dtor (WordToken * self)
Destroys a CommandToken object, freeing its members and re-initializing them to NULL in the process.
Parameters
self CommandToken object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
References token_dtor().
word_token_print_()
static void word_token_print_ (Token const *const self) static
Implementation of WordToken::Token::print().
Prints a pretty formatted display of the Token object.
Parameters
self pointer to WordToken object
References TokenVtbl::get_value, WordToken::super, and Token::vptr.
Referenced by word_token_ctor().
word_token_take_()
static void word_token_take_ (Token const *const self, StringIterator const *const iter) static
Implementation of WordToken::Token::take().
Iterates over a single word and then stores the copy.
Precondition
It is the caller's responsibility to ensure that the data being copied over is indeed a command token.
Parameters
self pointer to WordToken object
iter pointer to StringIterator object
References StringIteratorVtbl::munch_word, TokenVtbl::set_value, WordToken::super, Token::vptr, and StringIterator::vptr.
Referenced by word_token_ctor().