smallsh: src/smallsh.c File Reference
smallsh.c File Reference
Contains core shell functions.
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "builtins/builtins.h"
#include "error.h"
#include "events/events.h"
#include "globals.h"
#include "job-control/job-control.h"
#include "interpreter/parser.h"
#include "signals/installer.h"
Macros
#define _GNU_SOURCE
Functions
static int smallsh_eval (char *cmd)
Evaluate a command entered by the user.
static void smallsh_inspect_fg_only_mode_flag (void)
Inspects flag set by SIGTSTP handler to determine if foreground-only mode has been triggered.
static void smallsh_init (void)
Initialize shell and bring it to the foreground process group.
static ssize_t smallsh_read_input (char **cmd)
Prompt user for command and read input to cmd.
int main (void)
Run shell's main event loop until terminated.
Variables
volatile int smallsh_errno = 0
Detailed Description
Contains core shell functions.
Author
Mohamed Al-Hussein
Date
01 Feb 2022 Some of the ideas presented here were retrieved from the following source: https://www.gnu.org/software/libc/manual/html_node/Initializing-the-Shell.html
Definition in file smallsh.c.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 10 of file smallsh.c.
Function Documentation
main()
int main (void)
Run shell's main event loop until terminated.
Definition at line 331 of file smallsh.c.
 {
         ssize_t n_read;
         char *cmd;
         int status_;
         /* Setup event listener to catch signal events and related data. */
         status_ = events_init();
         if (status_ == -1) {
                 print_error_msg("events_init()");
                 _exit(1);
         }
         smallsh_init();
         job_table_ctor(&job_table);
         /* Run event loop forever until shell termination. */
         do {
                 /* Notify user about new job-control events. */
                 status_ = events_notify();
                 if (status_ == -1) {
                         print_error_msg("events_notify()");
                         status_ = EXIT_FAILURE;
                         break;
                 }
                 /* Read command from user. */
                 cmd = NULL;
                 n_read = smallsh_read_input(&cmd);
                 if (n_read == -1) {
                         print_error_msg("smallsh_read_input()");
                         status_ = EXIT_FAILURE;
                         break;
                 }
                 /*
                  * Check if SIGTSTP triggered fg-only mode on/off and update
                  * shell's state accordingly.
                  */
                 smallsh_inspect_fg_only_mode_flag();
                 /* Evaluate command. */
                 status_ = smallsh_eval(cmd);
                 if (status_ == -1) {
                         free(cmd);
                         status_ = EXIT_FAILURE;
                         break;
                 } else if (status_ == 1) {
                         free(cmd);
                         status_ = EXIT_SUCCESS;
                         break;
                 }
                 if (!smallsh_interactive_mode) {
 #ifdef TEST_SCRIPT
                         /* Add an extra newline to make output pretty. */
                         if (smallsh_line_buffer) {
                                 write(STDOUT_FILENO, "\n", 1);
                         }
                         smallsh_line_buffer = false;
 #endif
                 }
                 free(cmd);
         } while (1);
         exit_(status_);
 }
References events_init(), events_notify(), exit_(), job_table, job_table_ctor(), print_error_msg(), smallsh_eval(), smallsh_init(), smallsh_inspect_fg_only_mode_flag(), smallsh_interactive_mode, smallsh_line_buffer, and smallsh_read_input().
smallsh_eval()
static int smallsh_eval (char * cmd) static
Evaluate a command entered by the user.
Parameters
cmd command to evaluate
Returns
0 or 1 on success, -1 on failure
Definition at line 61 of file smallsh.c.
 {
         int status_;
         Parser parser;
         ssize_t n_stmts;
         Statement *stmt;
         Process *job_proc;
         StmtStdin *st_in;
         StmtStdout *st_out;
         char *infile, *outfile, *cmd_name;
         size_t n_in, n_out;
         bool foreground;
         Job *job;
         /* Parse command into statements for evaluation. */
         parser_ctor(&parser);
         n_stmts = parser.parse(&parser, cmd);
         if (n_stmts == -1) {
                 parser_dtor(&parser);
                 return -1; /* error */
         } else if (n_stmts == 0) {
                 parser_dtor(&parser);
                 smallsh_line_buffer = true;
                 return 0; /* no statements parsed */
         }
         /* Can have multiple statements, but we only want first one. */
         stmt = parser.get_statements(&parser)[0];
         /* Statement is not a builtin. */
         if ((stmt->stmt_flags & FLAGS_BUILTIN) == 0) {
                 /* Create process object. */
                 job_proc = malloc(sizeof(Process));
                 process_ctor(job_proc, stmt->stmt_cmd->cmd_argc,
                              stmt->stmt_cmd->cmd_argv, 0, false, 0);
                 st_in = stmt->stmt_stdin;
                 st_out = stmt->stmt_stdout;
                 n_in = st_in->stdin_num_streams;
                 n_out = st_out->stdout_num_streams;
                 if (n_in > 0) {
                         infile = st_in->stdin_streams[n_in - 1];
                 } else {
                         infile = NULL;
                 }
                 if (n_out > 0) {
                         outfile = st_out->stdout_streams[n_out - 1];
                         smallsh_line_buffer = true;
                 } else {
                         if (!smallsh_interactive_mode) {
 #ifdef TEST_SCRIPT
                                 /* Add newline to end of empty non-echo commands. */
                                 if (strcmp("echo", stmt->stmt_cmd->cmd_argv[0]) != 0) {
                                         write(STDOUT_FILENO, "\n", 1);
                                 }
 #endif
                         }
                         outfile = NULL;
                 }
                 if ((stmt->stmt_flags & FLAGS_BGCTRL) == 0 || smallsh_fg_only_mode) {
                         foreground = true;
                 } else{
                         foreground = false;
                 }
                 if (!smallsh_interactive_mode) {
 #ifdef TEST_SCRIPT
                         /* Some fun magic to make output pretty for test script. */
                         if (smallsh_fg_only_mode) {
                                 if ((stmt->stmt_flags & FLAGS_BGCTRL) != 0) {
                                         if (outfile == NULL) {
                                                 smallsh_line_buffer = true;
                                         }
                                 }
                         }
 #endif
                 }
                 /* Create job object. */
                 job = malloc(sizeof(Job));
                 job_ctor(job, cmd, job_proc, 0, infile, outfile, !foreground);
                 /* Add job to job table. */
                 job_table.add_job(&job_table, job);
                 /* Run job. */
                 status_ = job_control_launch_job(&job, foreground);
         }
         /* Statement is a builtin. */
         else {
                 /* Determine builtin name and run it. */
                 cmd_name = stmt->stmt_cmd->cmd_argv[0];
                 if (strcmp("exit", cmd_name) == 0) {
                         status_ = 1;
                         smallsh_line_buffer = true;
                 } else if (strcmp("cd", cmd_name) == 0) {
                         char *dirname = stmt->stmt_cmd->cmd_argv[1];
                         cd(dirname);
                         status_ = 0;
                         smallsh_line_buffer = true;
                 } else if (strcmp("status", cmd_name) == 0) {
                         status();
                         status_ = 0;
                 } else {
                         /* Error */
                         status_ = -1;
                 }
         }
         parser_dtor(&parser);
         return status_;
 }
References JobTable::add_job, cd(), StmtCmd::cmd_argc, StmtCmd::cmd_argv, FLAGS_BGCTRL, FLAGS_BUILTIN, Parser::get_statements, job_control_launch_job(), job_ctor(), job_table, Parser::parse, parser_ctor(), parser_dtor(), process_ctor(), smallsh_fg_only_mode, smallsh_interactive_mode, smallsh_line_buffer, status(), StmtStdin::stdin_num_streams, StmtStdin::stdin_streams, StmtStdout::stdout_num_streams, StmtStdout::stdout_streams, Statement::stmt_cmd, Statement::stmt_flags, Statement::stmt_stdin, and Statement::stmt_stdout.
Referenced by main().
smallsh_init()
static void smallsh_init (void) static
Initialize shell and bring it to the foreground process group.
Do not proceed until this is the case (but make an exception for the test script in this case).
Definition at line 205 of file smallsh.c.
 {
         int status_;
         /*
          * See if we are running interactively.
          *
          * When running from a test script, STDIN will not be a tty, and thus
          * we will not be in interactive mode.
          */
         smallsh_shell_terminal = STDIN_FILENO;
         smallsh_interactive_mode = isatty(smallsh_shell_terminal);
         if (smallsh_interactive_mode) {
                 smallsh_shell_pgid = getpgrp();
                 /* Loop until we are in the foreground. */
                 while (tcgetpgrp(smallsh_shell_terminal) != smallsh_shell_pgid) {
                         kill(-smallsh_shell_pgid, SIGTTIN);
                 }
         }
         /* Ignore interactive and job-control signals. */
         installer_install_job_control_signals();
         /* Put ourselves in our own process group. */
         smallsh_shell_pgid = getpid();
         errno = 0;
         status_ = setpgid(smallsh_shell_pgid, smallsh_shell_pgid);
         if (status_ == -1) {
                 if (errno == EPERM && smallsh_shell_pgid == getpgrp()) {
                         /*
                          * Process is session leader; do nothing.
                          *
                          * This is only triggered via CLion's run mode.
                          */
                 } else {
                         print_error_msg("Couldn't put shell in its own process group");
                         _exit(1);
                 }
         }
         if (smallsh_interactive_mode) {
                 /* Grab control of the terminal. */
                 tcsetpgrp(smallsh_shell_terminal, smallsh_shell_pgid);
         }
 }
References installer_install_job_control_signals(), print_error_msg(), smallsh_interactive_mode, smallsh_shell_pgid, and smallsh_shell_terminal.
Referenced by main().
smallsh_inspect_fg_only_mode_flag()
static void smallsh_inspect_fg_only_mode_flag (void) static
Inspects flag set by SIGTSTP handler to determine if foreground-only mode has been triggered.
Sets global variable smallsh_fg_only_mode accordingly.
Source: https://edstem.org/us/courses/16718/discussion/1067170
Definition at line 184 of file smallsh.c.
 {
         sigset_t mask;
         sigemptyset(&mask);
         sigaddset(&mask, SIGTSTP);
         sigprocmask(SIG_BLOCK, &mask, NULL);
         if (smallsh_fg_only_mode != smallsh_fg_only_mode_flag) {
                 smallsh_fg_only_mode = !smallsh_fg_only_mode;
         }
         sigprocmask(SIG_UNBLOCK, &mask, NULL);
 }
References smallsh_fg_only_mode, and smallsh_fg_only_mode_flag.
Referenced by main().
smallsh_read_input()
static ssize_t smallsh_read_input (char ** cmd) static
Prompt user for command and read input to cmd.
Parameters
cmd command to store input in
Returns
number of characters read
Definition at line 259 of file smallsh.c.
 {
         ssize_t n_read;
         size_t len;
         /* Prompt user for command. */
         if (write(STDOUT_FILENO, ": ", 2) == -1) {
                 print_error_msg("write");
                 _exit(1);
         }
         /* Read input command from user. */
         len = 0;
         errno = 0;
         n_read = getline(cmd, &len, stdin);
         if (n_read == -1 && errno != 0) {
                 print_error_msg("getline()");
                 return -1;
         }
 #ifdef TEST_SCRIPT_ECHO_COMMANDS
         /* Displays commands as if they were typed live in terminal */
         fprintf(stdout, "%s", *cmd);
         fflush(stdout);
 #endif
         return n_read;
 }
References print_error_msg().
Referenced by main().
Variable Documentation
smallsh_errno
volatile int smallsh_errno = 0
Definition at line 316 of file smallsh.c.