smallsh: include/builtins/status.h File Reference
status.h File Reference
status builtin command.
Functions
void status (void)
Displays last exit status value to user.
Detailed Description
status builtin command.
Author
Mohamed Al-Hussein
Date
03 Feb 2022
Definition in file status.h.
Function Documentation
status()
void status (void)
Displays last exit status value to user.
Definition at line 43 of file status.c.
 {
         if (!smallsh_interactive_mode) {
                 fprintf(stdout, "\nexit value %d\n", smallsh_errno);
         } else {
                 fprintf(stdout, "exit value %d\n", smallsh_errno);
         }
         fflush(stdout);
 }
References smallsh_errno, and smallsh_interactive_mode.
Referenced by cd(), events_init(), events_notify(), exit_(), handler_handle_sigchld(), handler_switch_disable_fg_only_mode(), handler_switch_enable_fg_only_mode(), installer_install_job_control_signals(), installer_install_sigchld_handler(), job_control_foreground_job(), job_control_launch_job(), job_control_wait_for_job(), job_table_update_(), process_ctor(), process_exec(), process_launch(), process_set_io_streams(), receiver_add(), sender_add(), sender_notify_sigchld(), and smallsh_eval().