smallsh: include/interpreter/statement.h File Reference
statement.h File Reference
For creating command statements to later be executed.
Data Structures
struct StmtCmd
Command object.
struct StmtStdin
STDIN Stream object.
struct StmtStdout
STDOUT Stream object.
struct Statement
A statement object is composed of the sub-statement objects required to execute a command.
Enumerations
enum StmtFlags { FLAGS_NONE = 0, FLAGS_BGCTRL = 1, FLAGS_BUILTIN = 2 }
Statement flags hold additional information on statement command boolean properties.
enum IORedirType { IOREDIR_STDIN = 0, IOREDIR_STDOUT = 1 }
IO Redirection types are used for determining which default IO stream to operate on.
Functions
Statement * statement_new (void)
Create and initialize a new Statement object.
void statement_del (Statement **stmt)
Deletes stmt and frees its associated data.
void statement_print (Statement const *self)
Pretty-prints a Statement object to stdout.
Detailed Description
For creating command statements to later be executed.
Author
Mohamed Al-Hussein
Date
02 Feb 2022
Definition in file statement.h.
Enumeration Type Documentation
IORedirType
enum IORedirType
IO Redirection types are used for determining which default IO stream to operate on.
Enumerator
IOREDIR_STDIN
stdin stream
IOREDIR_STDOUT
stdout stream
Definition at line 70 of file statement.h.
              {
         IOREDIR_STDIN = 0,
         IOREDIR_STDOUT = 1,
 } IORedirType;
StmtFlags
enum StmtFlags
Statement flags hold additional information on statement command boolean properties.
Enumerator
FLAGS_NONE
default flag
FLAGS_BGCTRL
background control flag
FLAGS_BUILTIN
builtin command flag
Definition at line 47 of file statement.h.
              {
         FLAGS_NONE = 0,
         FLAGS_BGCTRL = 1,
         FLAGS_BUILTIN = 2,
 } StmtFlags;
Function Documentation
statement_del()
void statement_del (Statement ** stmt)
Deletes stmt and frees its associated data.
Parameters
stmt Statement object to delete
Definition at line 70 of file statement.c.
 {
         // statement command delete
         for (size_t i = 0; i < (*stmt)->stmt_cmd->cmd_argc; i++) {
                 free((*stmt)->stmt_cmd->cmd_argv[i]);
                 (*stmt)->stmt_cmd->cmd_argv[i] = NULL;
         }
         free((*stmt)->stmt_cmd->cmd_argv);
         (*stmt)->stmt_cmd->cmd_argc = 0;
         (*stmt)->stmt_cmd->cmd_argv = NULL;
         free((*stmt)->stmt_cmd);
         (*stmt)->stmt_cmd = NULL;
         // statement io redirection: stdin delete
         for (size_t i = 0; i < (*stmt)->stmt_stdin->stdin_num_streams; i++) {
                 free((*stmt)->stmt_stdin->stdin_streams[i]);
                 (*stmt)->stmt_stdin->stdin_streams[i] = NULL;
         }
         free((*stmt)->stmt_stdin->stdin_streams);
         (*stmt)->stmt_stdin->stdin_num_streams = 0;
         (*stmt)->stmt_stdin->stdin_streams = NULL;
         free((*stmt)->stmt_stdin);
         (*stmt)->stmt_stdin = NULL;
         // statement io redirection: stdout delete
         for (size_t i = 0; i < (*stmt)->stmt_stdout->stdout_num_streams; i++) {
                 free((*stmt)->stmt_stdout->stdout_streams[i]);
                 (*stmt)->stmt_stdout->stdout_streams[i] = NULL;
         }
         free((*stmt)->stmt_stdout->stdout_streams);
         (*stmt)->stmt_stdout->stdout_num_streams = 0;
         (*stmt)->stmt_stdout->stdout_streams = NULL;
         free((*stmt)->stmt_stdout);
         (*stmt)->stmt_stdout = NULL;
         // statement flags delete
         (*stmt)->stmt_flags = FLAGS_NONE;
         // statement delete
         free(*stmt);
         *stmt = NULL;
 }
References FLAGS_NONE.
Referenced by parser_dtor().
statement_new()
Statement* statement_new (void)
Create and initialize a new Statement object.
Returns
new Statement object
Note
Caller is responsible for freeing structure via statement_del.
Definition at line 42 of file statement.c.
 {
         Statement *stmt = malloc(sizeof(Statement));
         // statement command init
         stmt->stmt_cmd = malloc(sizeof(StmtCmd));
         stmt->stmt_cmd->cmd_argc = 0;
         stmt->stmt_cmd->cmd_argv = malloc(sizeof(char *));
         stmt->stmt_cmd->cmd_argv[0] = NULL;
         // statement io redirection: stdin init
         stmt->stmt_stdin = malloc(sizeof(StmtStdin));
         stmt->stmt_stdin->stdin_num_streams = 0;
         stmt->stmt_stdin->stdin_streams = malloc(sizeof(char *));
         stmt->stmt_stdin->stdin_streams[0] = NULL;
         // statement io redirection: stdout init
         stmt->stmt_stdout = malloc(sizeof(StmtStdout));
         stmt->stmt_stdout->stdout_num_streams = 0;
         stmt->stmt_stdout->stdout_streams = malloc(sizeof(char *));
         stmt->stmt_stdout->stdout_streams[0] = NULL;
         // statement flags init
         stmt->stmt_flags = 0;
         return stmt;
 }
References StmtCmd::cmd_argc, StmtCmd::cmd_argv, StmtStdin::stdin_num_streams, StmtStdin::stdin_streams, StmtStdout::stdout_num_streams, StmtStdout::stdout_streams, Statement::stmt_cmd, Statement::stmt_flags, Statement::stmt_stdin, and Statement::stmt_stdout.
Referenced by parser_parse_statements_().
statement_print()
void statement_print (Statement const * self)
Pretty-prints a Statement object to stdout.
Parameters
self Statement object to print
Definition at line 123 of file statement.c.
 {
         printf("STATEMENT(\n");
         printf("\tFLAGS(\n");
         if (self->stmt_flags == FLAGS_BGCTRL) {
                 printf("\t\tBG_CTRL,\n");
         }
         printf("\t)\n");
         printf("\tCMD(\n");
         for (size_t i = 0; i < self->stmt_cmd->cmd_argc; i++) {
                 printf("\t\tARG [%zu] = %s,\n", i, self->stmt_cmd->cmd_argv[i]);
         }
         printf("\t)\n");
         printf("\tSTDIN(\n");
         for (size_t i = 0; i < self->stmt_stdin->stdin_num_streams; i++) {
                 printf("\t\t[%zu] = %s,\n", i, self->stmt_stdin->stdin_streams[i]);
         }
         printf("\t)\n");
         printf("\tSTDOUT(\n");
         for (size_t i = 0; i < self->stmt_stdout->stdout_num_streams; i++) {
                 printf("\t\t[%zu] = %s,\n", i, self->stmt_stdout->stdout_streams[i]);
         }
         printf("\t)\n");
         printf(")\n");
 }
References FLAGS_BGCTRL.
Referenced by parser_ctor().