smallsh: include/utils/string-iterator.h File Reference
string-iterator.h File Reference
For iterating over a single-line string.
#include <stdbool.h>
Data Structures
struct StringIterator
StringIterator object definition.
struct StringIteratorVtbl
VTable for a StringIterator object.
Macros
#define STRING_ITERATOR_EOL '\0'
Functions
void string_iterator_ctor (StringIterator *self, char *str)
Constructs a new StringIterator object.
void string_iterator_dtor (StringIterator *self)
Destroys a StringIterator object, freeing its members and re-initializing them to NULL in the process.
Detailed Description
For iterating over a single-line string.
Author
Mohamed Al-Hussein
Date
25 Jan 2022 This is a utility module for aiding in parsing strings into tokens. The functions defined here allow for iterating over a string character by character, until either a newline is reached or null terminator.
Definition in file string-iterator.h.
Macro Definition Documentation
STRING_ITERATOR_EOL
#define STRING_ITERATOR_EOL '\0'
signified end of line for iterator
Definition at line 16 of file string-iterator.h.
Function Documentation
string_iterator_ctor()
void string_iterator_ctor (StringIterator * self, char * str)
Constructs a new StringIterator object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self StringIterator object to initialize
str the string to iterate over
Note
A copy is made of string, so the caller can free/overwrite the string safely after calling this constructor. Note this also means the caller must destroy the data via calling the string_iterator_dtor function.
Examples
/home/runner/work/smallsh/smallsh/include/utils/string-iterator.h.
Definition at line 210 of file string-iterator.c.
 {
         static struct StringIteratorVtbl const vtbl = {
                 .has_next = &string_iterator_has_next_,
                 .munch_char = &string_iterator_munch_char_,
                 .munch_word = &string_iterator_munch_word_,
                 .next = &string_iterator_next_,
                 .peek = &string_iterator_peek_,
                 .slice = &string_iterator_slice_,
         };
         self->vptr = &vtbl;
         self->private = malloc(sizeof(struct StringIteratorPrivate));
         self->private->si_str = strdup(str);
         self->private->si_cur = &self->private->si_str[0];
 }
References StringIteratorVtbl::has_next, string_iterator_has_next_(), string_iterator_munch_char_(), string_iterator_munch_word_(), string_iterator_next_(), string_iterator_peek_(), and string_iterator_slice_().
Referenced by lexer_generate_tokens().
string_iterator_dtor()
void string_iterator_dtor (StringIterator * self)
Destroys a StringIterator object, freeing its members and re-initializing them to NULL in the process.
Parameters
self the StringIterator object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
Examples
/home/runner/work/smallsh/smallsh/include/utils/string-iterator.h.
Definition at line 227 of file string-iterator.c.
 {
         self->vptr = NULL;
         free((char *) self->private->si_str);
         self->private->si_str = NULL;
         self->private->si_cur = NULL;
         free(self->private);
         self->private = NULL;
 }
Referenced by lexer_generate_tokens().