smallsh: src/utils/string-iterator.c File Reference
string-iterator.c File Reference
For iterating over a single-line string.
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include "utils/string-iterator.h"
Data Structures
struct StringIteratorPrivate
Hides StringIterator members from client code.
Macros
#define _GNU_SOURCE
Functions
static bool string_iterator_has_next_ (StringIterator const *const self)
Implementation of StringIterator::has_next().
static char * string_iterator_munch_char_ (StringIterator const *const self)
Implementation of StringIterator::munchChar().
static char * string_iterator_munch_word_ (StringIterator const *const self)
Implementation of StringIterator::munchWord().
static const char * string_iterator_next_ (StringIterator const *const self)
Implementation of StringIterator::next().
static char * string_iterator_slice_ (StringIterator const *const self, const char *from)
static char string_iterator_peek_ (StringIterator const *const self, unsigned int offset)
Implementation of StringIterator::peek().
void string_iterator_ctor (StringIterator *self, char *str)
Constructs a new StringIterator object.
void string_iterator_dtor (StringIterator *self)
Destroys a StringIterator object, freeing its members and re-initializing them to NULL in the process.
Detailed Description
For iterating over a single-line string.
Author
Mohamed Al-Hussein
Date
25 Jan 2022 This is a utility module for aiding in parsing strings into tokens. The functions defined here allow for iterating over a string character by character, until either a newline is reached or null terminator.
Definition in file string-iterator.c.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 11 of file string-iterator.c.
Function Documentation
string_iterator_ctor()
void string_iterator_ctor (StringIterator * self, char * str)
Constructs a new StringIterator object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self StringIterator object to initialize
str the string to iterate over
Note
A copy is made of string, so the caller can free/overwrite the string safely after calling this constructor. Note this also means the caller must destroy the data via calling the string_iterator_dtor function.
Definition at line 210 of file string-iterator.c.
 {
         static struct StringIteratorVtbl const vtbl = {
                 .has_next = &string_iterator_has_next_,
                 .munch_char = &string_iterator_munch_char_,
                 .munch_word = &string_iterator_munch_word_,
                 .next = &string_iterator_next_,
                 .peek = &string_iterator_peek_,
                 .slice = &string_iterator_slice_,
         };
         self->vptr = &vtbl;
         self->private = malloc(sizeof(struct StringIteratorPrivate));
         self->private->si_str = strdup(str);
         self->private->si_cur = &self->private->si_str[0];
 }
References StringIteratorVtbl::has_next, string_iterator_has_next_(), string_iterator_munch_char_(), string_iterator_munch_word_(), string_iterator_next_(), string_iterator_peek_(), and string_iterator_slice_().
Referenced by lexer_generate_tokens().
string_iterator_dtor()
void string_iterator_dtor (StringIterator * self)
Destroys a StringIterator object, freeing its members and re-initializing them to NULL in the process.
Parameters
self the StringIterator object to destroy
Note
The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
Definition at line 227 of file string-iterator.c.
 {
         self->vptr = NULL;
         free((char *) self->private->si_str);
         self->private->si_str = NULL;
         self->private->si_cur = NULL;
         free(self->private);
         self->private = NULL;
 }
Referenced by lexer_generate_tokens().
string_iterator_has_next_()
static bool string_iterator_has_next_ (StringIterator const *const self) inline static
Implementation of StringIterator::has_next().
Parameters
self pointer to iterator object
Returns
true if iterator is positioned at parseable character, false otherwise
Definition at line 66 of file string-iterator.c.
 {
         char itr = *self->private->si_cur;
         return itr != '\0';
 }
Referenced by string_iterator_ctor().
string_iterator_munch_char_()
static char* string_iterator_munch_char_ (StringIterator const *const self) static
Implementation of StringIterator::munchChar().
Parameters
self pointer to iterator object
Returns
string containing copied character
Definition at line 77 of file string-iterator.c.
 {
         // grab character
         const char *start = self->vptr->next(self);
         // copy and return character
         char *slice = self->vptr->slice(self, start);
         return slice;
 }
Referenced by string_iterator_ctor().
string_iterator_munch_word_()
static char* string_iterator_munch_word_ (StringIterator const *const self) static
Implementation of StringIterator::munchWord().
Parameters
self pointer to iterator object
Returns
string containing copied word
Definition at line 92 of file string-iterator.c.
 {
         // grab word
         const char *start = self->vptr->next(self);
         char *slice;
         char c;
         while (self->vptr->has_next(self)) {
                 c = self->vptr->peek(self, 0);
                 switch (c) {
                         // stop at terminal character
                         case ' ':
                         case '\t':
                         case '\n':
                                 goto seek_fin;
                         default:
                                 break;
                 }
                 self->vptr->next(self);
         }
 seek_fin:
         // copy and return word
         slice = self->vptr->slice(self, start);
         return slice;
 }
Referenced by string_iterator_ctor().
string_iterator_next_()
static const char* string_iterator_next_ (StringIterator const *const self) inline static
Implementation of StringIterator::next().
Parameters
self pointer to iterator object
Returns
the character pointed to by the iterator
Definition at line 123 of file string-iterator.c.
 {
         const char *next = self->private->si_cur++;
         return next;
 }
Referenced by string_iterator_ctor().
string_iterator_peek_()
static char string_iterator_peek_ (StringIterator const *const self, unsigned int offset) inline static
Implementation of StringIterator::peek().
Parameters
self pointer to iterator object
offset how far ahead to peek
Returns
the character pointed to by the iterator
Definition at line 151 of file string-iterator.c.
 {
         const char *orig, *cur;
         char result;
         unsigned int pos;
         // store pointer to originating character
         orig = self->private->si_cur;
         // seek to offset or end of stream, whichever comes first
         pos = 0;
         do {
                 cur = self->vptr->next(self);
                 pos++;
         } while (pos <= offset && self->vptr->has_next(self));
         // check if iterator exhausted before reaching offset
         if (pos <= offset)
                 result = STRING_ITERATOR_EOL;
         else
                 result = *cur;
         // reset pointer to originating character
         self->private->si_cur = orig;
         return result;
 }
References STRING_ITERATOR_EOL.
Referenced by string_iterator_ctor().
string_iterator_slice_()
static char* string_iterator_slice_ (StringIterator const *const self, const char * from) static
Definition at line 129 of file string-iterator.c.
 {
         const char *l_bound = self->private->si_str;
         const char *r_bound = self->private->si_cur;
         if (from < l_bound || from >= r_bound) {
                 /* error out of bounds */
                 return NULL;
         }
         ptrdiff_t len = r_bound - from;
         char *slice = strndup(from, len);
         return slice;
 }
Referenced by string_iterator_ctor().