smallsh: StringIteratorVtbl Struct Reference
StringIteratorVtbl Struct Reference
VTable for a StringIterator object.
#include <string-iterator.h>
Data Fields
bool(* has_next)(StringIterator const *const self)
char *(* munch_char)(StringIterator const *const self)
Iterates over a single character and returns copy to caller.
char *(* munch_word)(StringIterator const *const self)
Iterates over a single word and returns copy to caller.
const char *(* next)(StringIterator const *const self)
Returns character that the iterator is pointing at, then advances to the next character.
char(* peek)(StringIterator const *const self, unsigned int offset)
Returns the nth character from the iterators cursor, without advancing to the it.
char *(* slice)(StringIterator const *const self, const char *from)
Returns a slice copied from the pointer starting at from and ending at the iterators current position - 1.
Detailed Description
VTable for a StringIterator object.
Iterator methods derived from this source: https://www.youtube.com/watch?v=hnlmbeQa31E
Examples
/home/runner/work/smallsh/smallsh/include/utils/string-iterator.h.
Definition at line 35 of file string-iterator.h.
Field Documentation
has_next
bool(* StringIteratorVtbl::has_next) (StringIterator const *const self)
Examples
/home/runner/work/smallsh/smallsh/include/utils/string-iterator.h.
Definition at line 72 of file string-iterator.h.
Referenced by lexer_generate_tokens(), and string_iterator_ctor().
munch_char
char*(* StringIteratorVtbl::munch_char) (StringIterator const *const self)
Iterates over a single character and returns copy to caller.
Iterator is updated to point to immediate character after end of copied character.
Parameters
self pointer to iterator object
Returns
string containing copied character
Note
The caller is responsible for freeing the return value after they are done using it.
Definition at line 84 of file string-iterator.h.
Referenced by bgctrl_token_take_(), comment_token_take_(), inputredir_token_take_(), newline_token_take_(), and outputredir_token_take_().
munch_word
char*(* StringIteratorVtbl::munch_word) (StringIterator const *const self)
Iterates over a single word and returns copy to caller.
A word is any sequence of characters, excluding a space character.
Iterator is updated to point to immediate character after end of copied word.
Parameters
self pointer to iterator object
Returns
string containing copied word
Note
The caller is responsible for freeing the return value after they are done using it.
Definition at line 102 of file string-iterator.h.
Referenced by word_token_take_().
next
const char*(* StringIteratorVtbl::next) (StringIterator const *const self)
Returns character that the iterator is pointing at, then advances to the next character.
Precondition
It is assumed that the iterator is always within bounds of the string it is iterating. Behavior is undefined if this is not the case.
Parameters
self pointer to iterator object
Returns
pointer to the character pointed to by the iterator
Definition at line 112 of file string-iterator.h.
Referenced by lexer_generate_tokens().
peek
char(* StringIteratorVtbl::peek) (StringIterator const *const self, unsigned int offset)
Returns the nth character from the iterators cursor, without advancing to the it.
If offset is equal to 0, then the character at the current cursor is retrieved.
If offset is positive, then the iterator peaks ahead of the cursor.
This function is provided to allow for look-ahead parsing by peeking at the next character in the iterator.
Precondition
It is assumed that the iterator is always within bounds of the string it is iterating. Behavior is undefined if this is not the case.
Parameters
self pointer to iterator object
offset how far ahead to peak
Returns
the nth character past the iterators cursor, or EOL if no more characters to seek past
Examples
/home/runner/work/smallsh/smallsh/include/utils/string-iterator.h.
Definition at line 138 of file string-iterator.h.
Referenced by lexer_generate_tokens().
slice
char*(* StringIteratorVtbl::slice) (StringIterator const *const self, const char *from)
Returns a slice copied from the pointer starting at from and ending at the iterators current position - 1.
Precondition
from must point to a valid address within the iterators internal string. This value should be retrieved by a prior call to StringIterator::next(). This function will perform bounds checking to verify the above is true, and will return NULL if it is not.
Parameters
self pointer to iterator object
from pointer to a position within iterator string
Returns
a slice of the iterator string on success, NULL on failure
Note
The caller is responsible for freeing the slice after they're done using it.
Definition at line 154 of file string-iterator.h.
The documentation for this struct was generated from the following file:
include/utils/string-iterator.h