smallsh: JobTable Struct Reference
JobTable Struct Reference
JobTable object.
#include <job-table.h>
Data Fields
void(* add_job)(struct JobTable const *const self, Job *job)
Add a job to the table.
void(* clean)(struct JobTable const *const self)
Clean the job table, displaying completed job statuses along the way.
Job *(* find_job)(struct JobTable const *const self, pid_t job_pgid)
Find a job within the table that has a matching job_pgid.
void(* killall)(struct JobTable const *const self)
Kills all children in table.
void(* list_jobs)(struct JobTable const *const self)
List all jobs in a pretty-printed format.
int(* update)(struct JobTable const *const self, pid_t pid, int status)
Update a job's status within the table.
struct JobTablePrivate * private
Contains internal data for table.
Detailed Description
JobTable object.
Field Documentation
add_job
void(* JobTable::add_job) (struct JobTable const *const self, Job *job)
Add a job to the table.
Parameters
self table to add job to
job job to add to table
Referenced by smallsh_eval().
clean
void(* JobTable::clean) (struct JobTable const *const self)
Clean the job table, displaying completed job statuses along the way.
Parameters
self table to clean
Referenced by events_notify().
find_job
Job*(* JobTable::find_job) (struct JobTable const *const self, pid_t job_pgid)
Find a job within the table that has a matching job_pgid.
Parameters
self table to search for job in
job_pgid job PGID to search for
Returns
Job object if found, NULL if not
killall
void(* JobTable::killall) (struct JobTable const *const self)
Kills all children in table.
Called on program exit to clean up any unterminated children the shell created.
Parameters
self table containing child processes
Referenced by exit_().
list_jobs
void(* JobTable::list_jobs) (struct JobTable const *const self)
List all jobs in a pretty-printed format.
Parameters
self table to print
private
struct JobTablePrivate* JobTable::private
Contains internal data for table.
update
int(* JobTable::update) (struct JobTable const *const self, pid_t pid, int status)
Update a job's status within the table.
Parameters
self table where job resides
pid job's PID
status status to give job
Returns
0 if job was found and updated, -1 otherwise
Referenced by receiver_cb_sigchld().
The documentation for this struct was generated from the following file:
include/job-control/job-table.h