smallsh: TokenIteratorVtbl Struct Reference
TokenIteratorVtbl Struct Reference
VTable for TokenIterator object.
#include <token-iterator.h>
Data Fields
bool(* has_next)(TokenIterator const *const self)
Let's caller know if there are any more tokens left to parse from iterable.
Token *(* next)(TokenIterator const *const self)
Returns the token the iterator is pointing at, then advances to the next token.
Token(* peek)(TokenIterator const *const self, unsigned int offset)
Returns the nth token from the iterators cursor, without advancing to it.
Detailed Description
VTable for TokenIterator object.
Iterator methods derived from this source: https://www.youtube.com/watch?v=hnlmbeQa31E
Definition at line 31 of file token-iterator.h.
Field Documentation
has_next
bool(* TokenIteratorVtbl::has_next) (TokenIterator const *const self)
Let's caller know if there are any more tokens left to parse from iterable.
The iterable is deemed exhausted under two conditions:
The iterator is pointing at the last token in the iterable.
The next token in the iterable is a newline token.
Parameters
self pointer to iterator object
Returns
true if iterator is positioned at a valid token, false otherwise
Definition at line 48 of file token-iterator.h.
Referenced by parser_parse_cmd_(), parser_parse_statements_(), and token_iterator_ctor().
next
Token*(* TokenIteratorVtbl::next) (TokenIterator const *const self)
Returns the token the iterator is pointing at, then advances to the next token.
Precondition
It is assumed that the iterator can retrieve the next token. Behavior is undefined if this is not the case. Caller should use TokenIterator::has_next() to verify before calling this method.
Parameters
self pointer to iterator object
Returns
pointer to next token in iterable
Definition at line 59 of file token-iterator.h.
Referenced by parser_parse_cmd_(), parser_parse_ioredir_(), and parser_parse_statements_().
peek
Token(* TokenIteratorVtbl::peek) (TokenIterator const *const self, unsigned int offset)
Returns the nth token from the iterators cursor, without advancing to it.
If offset is equal to 0, then the token at the current position of the iterator is retrieved.
If offset is positive, then the iterator will return the token that is @offset elements ahead of the current cursor.
This function is provided to allow for look-ahead parsing by peeking at the next token in the iterator.
Parameters
self pointer to iterator object
offset how far ahead to peek
Returns
the nth character past the iterators cursor, or an empty NewlineToken object if no more tokens to seek past
Definition at line 82 of file token-iterator.h.
Referenced by parser_parse_cmd_(), parser_parse_ioredir_(), and parser_parse_statements_().
The documentation for this struct was generated from the following file:
include/interpreter/token-iterator.h