smallsh: TokenVtbl Struct Reference
TokenVtbl Struct Reference
VTable for a Token object.
#include <token.h>
Data Fields
TokenType(* get_type)(Token const *const self)
Returns the token's type identifier.
char *(* get_value)(Token const *const self)
Returns copy of the string stored by the token.
void(* print)(Token const *const self)
Prints a pretty-formatted version of self.
void(* set_value)(Token const *const self, const char *const value)
Copies value into self's value field.
void(* take)(Token const *const self, StringIterator const *const iter)
Virtual method definition for 'taking', or storing a string as part of the token's value.
Detailed Description
VTable for a Token object.
take method derived from this source: https://www.youtube.com/watch?v=ikw4V_x-CFI
Definition at line 41 of file token.h.
Field Documentation
get_type
TokenType(* TokenVtbl::get_type) (Token const *const self)
Returns the token's type identifier.
Parameters
self pointer to Token object
Returns
the token's type identifier
Definition at line 47 of file token.h.
Referenced by bgctrl_token_ctor(), comment_token_ctor(), inputredir_token_ctor(), newline_token_ctor(), outputredir_token_ctor(), token_ctor(), token_iterator_has_next_(), and word_token_ctor().
get_value
char*(* TokenVtbl::get_value) (Token const *const self)
Returns copy of the string stored by the token.
Parameters
self pointer to Token object
Returns
copy of string stored by self
Note
The caller is responsible for freeing the return value when they're done using it.
Definition at line 56 of file token.h.
Referenced by bgctrl_token_print_(), comment_token_print_(), inputredir_token_print_(), outputredir_token_print_(), parser_parse_cmd_(), parser_parse_ioredir_(), and word_token_print_().
print
void(* TokenVtbl::print) (Token const *const self)
Prints a pretty-formatted version of self.
Parameters
self pointer to Token object
Definition at line 62 of file token.h.
set_value
void(* TokenVtbl::set_value) (Token const *const self, const char *const value)
Copies value into self's value field.
Parameters
self pointer to Token object
value the string to copy to self
Definition at line 69 of file token.h.
Referenced by bgctrl_token_take_(), comment_token_take_(), inputredir_token_take_(), newline_token_take_(), outputredir_token_take_(), and word_token_take_().
take
void(* TokenVtbl::take) (Token const *const self, StringIterator const *const iter)
Virtual method definition for 'taking', or storing a string as part of the token's value.
Implementations of this method should define how to parse a string using the @iter iterator in order to retrieve a valid token string to be stored at TokenPrivate::value.
Parameters
self pointer to Token object
iter pointer to StringIterator object
Definition at line 83 of file token.h.
The documentation for this struct was generated from the following file:
include/interpreter/token.h