smallsh: src/interpreter/token-iterator.c File Reference
token-iterator.c File Reference
For iterating over a collection of tokens.
#include "interpreter/token-iterator.h"
Data Structures
struct TokenIteratorPrivate
Hides TokenIterator members from client code.
Functions
static bool token_iterator_has_next_ (TokenIterator const *const self)
Implementation of TokenIterator::has_next().
static Token * token_iterator_next_ (TokenIterator const *const self)
Implementation of TokenIterator::next().
static Token token_iterator_peek_ (TokenIterator const *const self, unsigned int offset)
Implementation of TokenIterator::peek().
void token_iterator_ctor (TokenIterator *self, size_t len, Token *tok[len])
Constructs a new TokenIterator object.
void token_iterator_dtor (TokenIterator *self)
Destroys a TokenIterator object, freeing its members and re-initializing them to NULL in the process.
Detailed Description
For iterating over a collection of tokens.
Author
Mohamed Al-Hussein
Date
28 Jan 2022
Definition in file token-iterator.c.
Function Documentation
token_iterator_ctor()
void token_iterator_ctor (TokenIterator * self, size_t len, Token * tok[len])
Constructs a new TokenIterator object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Precondition
if tokens does not contain exactly len tokens ,then tokens must be terminated by a newline token to signify the end of the stream. Behavior is undefined if this is not the case.
Parameters
self TokenIterator object to initialize
len length of the token array
tok the token array to iterate over
Note
No copy is made of tokens, so the caller must not free or modify the parameter until they are finished using the iterator. Likewise, the caller cannot guarantee that the tokens array is left unmodified at the end of the iterators lifespan.
Definition at line 145 of file token-iterator.c.
 {
         static struct TokenIteratorVtbl const vtbl = {
                 .has_next = &token_iterator_has_next_,
                 .next = &token_iterator_next_,
                 .peek = &token_iterator_peek_,
         };
         self->vptr = &vtbl;
         self->private = malloc(sizeof(struct TokenIteratorPrivate));
         self->private->ti_len = len;
         self->private->ti_tok = tok;
         self->private->ti_cur = 0;
 }
References TokenIteratorVtbl::has_next, token_iterator_has_next_(), token_iterator_next_(), token_iterator_peek_(), and Token::vptr.
Referenced by parser_parse_statements_().
token_iterator_dtor()
void token_iterator_dtor (TokenIterator * self)
Destroys a TokenIterator object, freeing its members and re-initializing them to NULL in the process.
The exception to this is that the tokens array is not freed, as that is up to the caller to perform.
Parameters
self The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
Definition at line 160 of file token-iterator.c.
 {
         self->vptr = NULL;
         self->private->ti_len = 0;
         self->private->ti_tok = NULL;
         self->private->ti_cur = 0;
         free(self->private);
         self->private = NULL;
 }
Referenced by parser_parse_statements_().
token_iterator_has_next_()
static bool token_iterator_has_next_ (TokenIterator const *const self) inline static
Implementation of TokenIterator::has_next().
Parameters
self pointer to iterator object
Returns
true if iterator is positioned at a parseable token, false otherwise
Definition at line 54 of file token-iterator.c.
 {
         Token iter;
         ShellTokenType type;
         bool in_bounds;
         // grab last token to check if it's a newline token
         iter = *self->private->ti_tok[self->private->ti_cur];
         type = (ShellTokenType) iter.vptr->get_type(&iter);
         // cursor can be at most len - 1
         in_bounds = self->private->ti_cur < self->private->ti_len;
         return in_bounds && type != TOK_CTRL_NEWLINE;
 }
References TokenVtbl::get_type, Token::private, TOK_CTRL_NEWLINE, and Token::vptr.
Referenced by token_iterator_ctor().
token_iterator_next_()
static Token* token_iterator_next_ (TokenIterator const *const self) inline static
Implementation of TokenIterator::next().
Parameters
self pointer to iterator object
Returns
pointer to next token in iterable
Definition at line 75 of file token-iterator.c.
 {
         return self->private->ti_tok[self->private->ti_cur++];
 }
References Token::private.
Referenced by token_iterator_ctor().
token_iterator_peek_()
static Token token_iterator_peek_ (TokenIterator const *const self, unsigned int offset) inline static
Implementation of TokenIterator::peek().
Parameters
self pointer to iterator object
offset how far ahead to peek
Returns
token pointed to by iterator at given offset
Definition at line 86 of file token-iterator.c.
 {
         Token *cur;
         Token result;
         // store original index
         size_t orig = self->private->ti_cur;
         unsigned int pos = 0;
         do {
                 cur = self->vptr->next(self);
                 pos++;
         } while (pos <= offset && self->vptr->has_next(self));
         if (pos <= offset) {
                 // newline token acts as null terminator for token array
                 NewlineToken n;
                 newline_token_ctor(&n);
                 result = *(Token *) &n;
         } else {
                 result = *cur;
         }
         self->private->ti_cur = orig;
         return result;
 }
References newline_token_ctor(), Token::private, and Token::vptr.
Referenced by token_iterator_ctor().