smallsh: src/interpreter/token.c File Reference
token.c File Reference
For parsing and storing tokens.
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include "interpreter/token.h"
Data Structures
struct TokenPrivate
Hides Token members from sub-classes and client code.
Macros
#define _GNU_SOURCE
Functions
static void token_print_ (Token const *const self)
Virtual method definition for pretty printing a Token object.
static void token_take_ (Token const *const self, StringIterator const *const iter)
Virtual method definition for 'taking', or storing a string as part of the token's value.
void token_ctor (Token *self, TokenType type)
Constructs a new Token object.
void token_dtor (Token *self)
Destroys a Token object, freeing its members and re-initializing them to NULL in the process.
TokenType token_get_type_ (const Token *self)
Implementation of Token::getType().
char * token_get_value_ (const Token *self)
Implementation of Token::getValue().
void token_set_value_ (const Token *self, const char *value)
Implementation of Token::setValue().
Detailed Description
For parsing and storing tokens.
Author
Mohamed Al-Hussein
Date
25 Jan 2022 This is a base class for parsing strings into categorized tokens. This class is not meant to be used on its own, rather it should be inherited and implemented into more specific token classes.
Definition in file token.c.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 11 of file token.c.
Function Documentation
token_ctor()
void token_ctor (Token * self, TokenType type)
Constructs a new Token object.
This is a base class constructor and should only be called via a child class constructor.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Parameters
self Token object to initialize
type TokenType to to assign to self
Definition at line 124 of file token.c.
 {
         static struct TokenVtbl const vtbl = {
                 .get_type = &token_get_type_,
                 .get_value = &token_get_value_,
                 .print = &token_print_,
                 .set_value = &token_set_value_,
                 .take = &token_take_,
         };
         self->vptr = &vtbl;
         self->private = malloc(sizeof(struct TokenPrivate));
         self->private->tok_type = type;
         self->private->tok_value = NULL;
 }
References TokenVtbl::get_type, token_get_type_(), token_get_value_(), token_print_(), token_set_value_(), and token_take_().
Referenced by bgctrl_token_ctor(), comment_token_ctor(), inputredir_token_ctor(), newline_token_ctor(), outputredir_token_ctor(), and word_token_ctor().
token_dtor()
void token_dtor (Token * self)
Destroys a Token object, freeing its members and re-initializing them to NULL in the process.
This is a base class destructor and should only be called via a child class destructor.
Parameters
self pointer to Token object
Definition at line 140 of file token.c.
 {
         self->vptr = NULL;
         self->private->tok_type = TOK_0;
         free(self->private->tok_value);
         self->private->tok_value = NULL;
         free(self->private);
         self->private = NULL;
 }
References TOK_0.
Referenced by bgctrl_token_dtor(), comment_token_dtor(), inputredir_token_dtor(), newline_token_dtor(), outputredir_token_dtor(), parser_dtor(), and word_token_dtor().
token_get_type_()
TokenType token_get_type_ (Token const * self) inline
Implementation of Token::getType().
Parameters
self pointer to Token object
Returns
the token's type identifier
Definition at line 163 of file token.c.
 {
         return self->private->tok_type;
 }
Referenced by bgctrl_token_ctor(), comment_token_ctor(), inputredir_token_ctor(), newline_token_ctor(), outputredir_token_ctor(), token_ctor(), and word_token_ctor().
token_get_value_()
char* token_get_value_ (Token const * self)
Implementation of Token::getValue().
Parameters
self pointer to Token object
Returns
copy of string stored by self
Note
The caller is responsible for freeing the return value when they're done using it.
Definition at line 168 of file token.c.
 {
         if (self->private->tok_value == NULL)
                 return NULL;
         char *value = strdup(self->private->tok_value);
         return value;
 }
Referenced by bgctrl_token_ctor(), comment_token_ctor(), inputredir_token_ctor(), newline_token_ctor(), outputredir_token_ctor(), token_ctor(), and word_token_ctor().
token_print_()
static void token_print_ (Token const *const self) static
Virtual method definition for pretty printing a Token object.
Parameters
self pointer to Token object
Definition at line 70 of file token.c.
 {
         (void) self;
         assert(0);
 }
Referenced by token_ctor().
token_set_value_()
void token_set_value_ (Token const * self, const char * value)
Implementation of Token::setValue().
Parameters
self pointer to Token object
value the string to copy to self
Definition at line 177 of file token.c.
 {
         // free original value before re-initializing it with new data
         if (self->private->tok_value != NULL) {
                 free(self->private->tok_value);
                 self->private->tok_value = NULL;
         }
         self->private->tok_value = strdup(value);
 }
Referenced by bgctrl_token_ctor(), comment_token_ctor(), inputredir_token_ctor(), newline_token_ctor(), outputredir_token_ctor(), token_ctor(), and word_token_ctor().
token_take_()
static void token_take_ (Token const *const self, StringIterator const *const iter) static
Virtual method definition for 'taking', or storing a string as part of the token's value.
Implementations of this method should define how to parse a string using the @iter iterator in order to retrieve a valid token string to be stored at TokenPrivate::value.
Parameters
self pointer to Token object
iter pointer to StringIterator object
Definition at line 87 of file token.c.
 {
         (void) self;
         (void) iter;
         assert(0);
 }
Referenced by token_ctor().