smallsh: include/interpreter/token-iterator.h File Reference
token-iterator.h File Reference
For iterating over a collection of tokens.
#include <stdlib.h>
#include "shell-tokens.h"
Data Structures
struct TokenIterator
TokenIterator object definition.
struct TokenIteratorVtbl
VTable for TokenIterator object.
Functions
void token_iterator_ctor (TokenIterator *self, size_t len, Token *tok[len])
Constructs a new TokenIterator object.
void token_iterator_dtor (TokenIterator *self)
Destroys a TokenIterator object, freeing its members and re-initializing them to NULL in the process.
Detailed Description
For iterating over a collection of tokens.
Author
Mohamed Al-Hussein
Date
28 Jan 2022
Definition in file token-iterator.h.
Function Documentation
token_iterator_ctor()
void token_iterator_ctor (TokenIterator * self, size_t len, Token * tok[len])
Constructs a new TokenIterator object.
The general implementation of a vtable, usage of const for the main object, and other OOP concepts were derived from this publication.
Source: https://www.state-machine.com/doc/AN_OOP_in_C.pdf*
Precondition
if tokens does not contain exactly len tokens ,then tokens must be terminated by a newline token to signify the end of the stream. Behavior is undefined if this is not the case.
Parameters
self TokenIterator object to initialize
len length of the token array
tok the token array to iterate over
Note
No copy is made of tokens, so the caller must not free or modify the parameter until they are finished using the iterator. Likewise, the caller cannot guarantee that the tokens array is left unmodified at the end of the iterators lifespan.
Definition at line 145 of file token-iterator.c.
 {
         static struct TokenIteratorVtbl const vtbl = {
                 .has_next = &token_iterator_has_next_,
                 .next = &token_iterator_next_,
                 .peek = &token_iterator_peek_,
         };
         self->vptr = &vtbl;
         self->private = malloc(sizeof(struct TokenIteratorPrivate));
         self->private->ti_len = len;
         self->private->ti_tok = tok;
         self->private->ti_cur = 0;
 }
References TokenIteratorVtbl::has_next, token_iterator_has_next_(), token_iterator_next_(), token_iterator_peek_(), and Token::vptr.
Referenced by parser_parse_statements_().
token_iterator_dtor()
void token_iterator_dtor (TokenIterator * self)
Destroys a TokenIterator object, freeing its members and re-initializing them to NULL in the process.
The exception to this is that the tokens array is not freed, as that is up to the caller to perform.
Parameters
self The caller is responsible for freeing self afterwards if it was originally allocated on the heap.
Definition at line 160 of file token-iterator.c.
 {
         self->vptr = NULL;
         self->private->ti_len = 0;
         self->private->ti_tok = NULL;
         self->private->ti_cur = 0;
         free(self->private);
         self->private = NULL;
 }
Referenced by parser_parse_statements_().